#![allow(non_snake_case)]

mod AirportIcon;
pub use AirportIcon::*;
mod AstronautHelmetIcon;
pub use AstronautHelmetIcon::*;
mod AxeIcon;
pub use AxeIcon::*;
mod BeachPaddleIcon;
pub use BeachPaddleIcon::*;
mod BeachUmbrellaIcon;
pub use BeachUmbrellaIcon::*;
mod BigBenIcon;
pub use BigBenIcon::*;
mod BinocularsIcon;
pub use BinocularsIcon::*;
mod BlueMosqueIcon;
pub use BlueMosqueIcon::*;
mod BrandenburgGateIcon;
pub use BrandenburgGateIcon::*;
mod BuddhistTempleIcon;
pub use BuddhistTempleIcon::*;
mod BurjAlArabIcon;
pub use BurjAlArabIcon::*;
mod CalendarCheckInIcon;
pub use CalendarCheckInIcon::*;
mod CalendarCheckOutIcon;
pub use CalendarCheckOutIcon::*;
mod CamperVanIcon;
pub use CamperVanIcon::*;
mod CampgroundIcon;
pub use CampgroundIcon::*;
mod CampingLanternIcon;
pub use CampingLanternIcon::*;
mod CastleIcon;
pub use CastleIcon::*;
mod ChristTheRedeemerIcon;
pub use ChristTheRedeemerIcon::*;
mod ChurchIcon;
pub use ChurchIcon::*;
mod CircleInfoIcon;
pub use CircleInfoIcon::*;
mod CnTowerIcon;
pub use CnTowerIcon::*;
mod ColosseumIcon;
pub use ColosseumIcon::*;
mod ConciergeIcon;
pub use ConciergeIcon::*;
mod DirectionSignRightIcon;
pub use DirectionSignRightIcon::*;
mod EiffelTowerIcon;
pub use EiffelTowerIcon::*;
mod EmpireStateIcon;
pub use EmpireStateIcon::*;
mod FlightTransferIcon;
pub use FlightTransferIcon::*;
mod GoldenGateBridgeIcon;
pub use GoldenGateBridgeIcon::*;
mod GreatWallIcon;
pub use GreatWallIcon::*;
mod HeavyDutyVehicleIcon;
pub use HeavyDutyVehicleIcon::*;
mod HoneymoonIcon;
pub use HoneymoonIcon::*;
mod HotelIcon;
pub use HotelIcon::*;
mod HotelSignIcon;
pub use HotelSignIcon::*;
mod IglooIcon;
pub use IglooIcon::*;
mod JapaneseTempleIcon;
pub use JapaneseTempleIcon::*;
mod LeaningTowerIcon;
pub use LeaningTowerIcon::*;
mod LighthouseIcon;
pub use LighthouseIcon::*;
mod LuggageIcon;
pub use LuggageIcon::*;
mod LuggageSearchIcon;
pub use LuggageSearchIcon::*;
mod LuggageTrolleyIcon;
pub use LuggageTrolleyIcon::*;
mod MosqueIcon;
pub use MosqueIcon::*;
mod PassportIcon;
pub use PassportIcon::*;
mod People3Icon;
pub use People3Icon::*;
mod PeopleIcon;
pub use PeopleIcon::*;
mod PyramidsIcon;
pub use PyramidsIcon::*;
mod RoadSignLeftIcon;
pub use RoadSignLeftIcon::*;
mod SagradaFamiliaIcon;
pub use SagradaFamiliaIcon::*;
mod SaintBasilCathedralIcon;
pub use SaintBasilCathedralIcon::*;
mod SecurityGateIcon;
pub use SecurityGateIcon::*;
mod ServiceBellIcon;
pub use ServiceBellIcon::*;
mod SphinxIcon;
pub use SphinxIcon::*;
mod StatueOfLibertyIcon;
pub use StatueOfLibertyIcon::*;
mod SunglassesIcon;
pub use SunglassesIcon::*;
mod SwissKnifeIcon;
pub use SwissKnifeIcon::*;
mod SydneyOperaHouseIcon;
pub use SydneyOperaHouseIcon::*;
mod TeepeeIcon;
pub use TeepeeIcon::*;
mod TempleIcon;
pub use TempleIcon::*;
mod ToriiGateIcon;
pub use ToriiGateIcon::*;
mod TravelBagIcon;
pub use TravelBagIcon::*;
mod UserPolice2Icon;
pub use UserPolice2Icon::*;
mod WhiteHouseIcon;
pub use WhiteHouseIcon::*;
