#![allow(non_snake_case)]

mod BlockquoteIcon;
pub use BlockquoteIcon::*;
mod CirclePencilIcon;
pub use CirclePencilIcon::*;
mod ClosingQuotationMark2Icon;
pub use ClosingQuotationMark2Icon::*;
mod ClosingQuotationMarkIcon;
pub use ClosingQuotationMarkIcon::*;
mod DotsIcon;
pub use DotsIcon::*;
mod FloatLeftIcon;
pub use FloatLeftIcon::*;
mod FloatRightIcon;
pub use FloatRightIcon::*;
mod LineDashedIcon;
pub use LineDashedIcon::*;
mod Link2Icon;
pub use Link2Icon::*;
mod Link2SlashIcon;
pub use Link2SlashIcon::*;
mod Link3Icon;
pub use Link3Icon::*;
mod Link4Icon;
pub use Link4Icon::*;
mod Link4SlashIcon;
pub use Link4SlashIcon::*;
mod Link5Icon;
pub use Link5Icon::*;
mod Link5SlashIcon;
pub use Link5SlashIcon::*;
mod Link6Icon;
pub use Link6Icon::*;
mod Link6MinusIcon;
pub use Link6MinusIcon::*;
mod Link6PlusIcon;
pub use Link6PlusIcon::*;
mod Link7Icon;
pub use Link7Icon::*;
mod Link7SlashIcon;
pub use Link7SlashIcon::*;
mod LinkBrokenIcon;
pub use LinkBrokenIcon::*;
mod LinkIcon;
pub use LinkIcon::*;
mod LinkSlashIcon;
pub use LinkSlashIcon::*;
mod ListFavs2Icon;
pub use ListFavs2Icon::*;
mod ListFavsIcon;
pub use ListFavsIcon::*;
mod OpeningQuotationMarkIcon;
pub use OpeningQuotationMarkIcon::*;
mod OrderedListIcon;
pub use OrderedListIcon::*;
mod ParagraphAddIcon;
pub use ParagraphAddIcon::*;
mod ParagraphCheckIcon;
pub use ParagraphCheckIcon::*;
mod ParagraphClearIcon;
pub use ParagraphClearIcon::*;
mod ParagraphIcon;
pub use ParagraphIcon::*;
mod PilcrowIcon;
pub use PilcrowIcon::*;
mod Post2Icon;
pub use Post2Icon::*;
mod PostIcon;
pub use PostIcon::*;
mod QuoteIcon;
pub use QuoteIcon::*;
mod SpellCheckIcon;
pub use SpellCheckIcon::*;
mod StringContainsIcon;
pub use StringContainsIcon::*;
mod StringDoesNotContainIcon;
pub use StringDoesNotContainIcon::*;
mod StringEndsWithIcon;
pub use StringEndsWithIcon::*;
mod StringStartsWithIcon;
pub use StringStartsWithIcon::*;
mod SubscriptIcon;
pub use SubscriptIcon::*;
mod SuperscriptIcon;
pub use SuperscriptIcon::*;
mod TextASparkleIcon;
pub use TextASparkleIcon::*;
mod TextBoldIcon;
pub use TextBoldIcon::*;
mod TextColumnsIcon;
pub use TextColumnsIcon::*;
mod TextInputIcon;
pub use TextInputIcon::*;
mod TextPromptIcon;
pub use TextPromptIcon::*;
mod TextScaleYIcon;
pub use TextScaleYIcon::*;
mod UnorderedList2Icon;
pub use UnorderedList2Icon::*;
mod UnorderedListIcon;
pub use UnorderedListIcon::*;
