pub struct Templates {
    pub clickhouse: &'static str,
    pub elasticsearch: &'static str,
    pub grafana: &'static str,
    pub jaeger: &'static str,
    pub keycloak: &'static str,
    pub libretranslate: &'static str,
    pub maildev: &'static str,
    pub memcached: &'static str,
    pub minio: &'static str,
    pub mongodb: &'static str,
    pub mysql: &'static str,
    pub nats: &'static str,
    pub postgres: &'static str,
    pub prometheus: &'static str,
    pub rabbitmq: &'static str,
    pub redis: &'static str,
    pub temporal: &'static str,
    pub vault: &'static str,
}

pub const TEMPLATES: Templates = Templates {
    clickhouse: include_str!("./clickhouse.txt"),
    elasticsearch: include_str!("./elasticsearch.txt"),
    grafana: include_str!("./grafana.txt"),
    jaeger: include_str!("./jaeger.txt"),
    keycloak: include_str!("./keycloak.txt"),
    libretranslate: include_str!("./libretranslate.txt"),
    maildev: include_str!("./maildev.txt"),
    memcached: include_str!("./memcached.txt"),
    minio: include_str!("./minio.txt"),
    mongodb: include_str!("./mongodb.txt"),
    mysql: include_str!("./mysql.txt"),
    nats: include_str!("./nats.txt"),
    postgres: include_str!("./postgres.txt"),
    prometheus: include_str!("./prometheus.txt"),
    rabbitmq: include_str!("./rabbitmq.txt"),
    redis: include_str!("./redis.txt"),
    temporal: include_str!("./temporal.txt"),
    vault: include_str!("./vault.txt"),
};
