#![allow(non_snake_case)]

mod ApronIcon;
pub use ApronIcon::*;
mod AromaDiffuserIcon;
pub use AromaDiffuserIcon::*;
mod BabyOnesieIcon;
pub use BabyOnesieIcon::*;
mod Backpack2Icon;
pub use Backpack2Icon::*;
mod BackpackIcon;
pub use BackpackIcon::*;
mod BagIcon;
pub use BagIcon::*;
mod BagShopping2Icon;
pub use BagShopping2Icon::*;
mod BagShoppingIcon;
pub use BagShoppingIcon::*;
mod BarberPoleIcon;
pub use BarberPoleIcon::*;
mod BeardIcon;
pub use BeardIcon::*;
mod BeautyCreamIcon;
pub use BeautyCreamIcon::*;
mod BeltIcon;
pub use BeltIcon::*;
mod BikiniIcon;
pub use BikiniIcon::*;
mod BlazerIcon;
pub use BlazerIcon::*;
mod BootIcon;
pub use BootIcon::*;
mod BootsIcon;
pub use BootsIcon::*;
mod BowTieIcon;
pub use BowTieIcon::*;
mod BraIcon;
pub use BraIcon::*;
mod ButtonIcon;
pub use ButtonIcon::*;
mod CapIcon;
pub use CapIcon::*;
mod ChefUniformIcon;
pub use ChefUniformIcon::*;
mod CombIcon;
pub use CombIcon::*;
mod CorsetIcon;
pub use CorsetIcon::*;
mod DiamondIcon;
pub use DiamondIcon::*;
mod DressIcon;
pub use DressIcon::*;
mod EyebrowEyelashesIcon;
pub use EyebrowEyelashesIcon::*;
mod EyelashIcon;
pub use EyelashIcon::*;
mod EyelinerIcon;
pub use EyelinerIcon::*;
mod FacePowderIcon;
pub use FacePowderIcon::*;
mod FlipFlopIcon;
pub use FlipFlopIcon::*;
mod GemIcon;
pub use GemIcon::*;
mod GlassesIcon;
pub use GlassesIcon::*;
mod GlovesIcon;
pub use GlovesIcon::*;
mod GymBagIcon;
pub use GymBagIcon::*;
mod HairClipperIcon;
pub use HairClipperIcon::*;
mod HairDryerIcon;
pub use HairDryerIcon::*;
mod HairGelIcon;
pub use HairGelIcon::*;
mod HairStraightenerIcon;
pub use HairStraightenerIcon::*;
mod HandWashIcon;
pub use HandWashIcon::*;
mod HandbagIcon;
pub use HandbagIcon::*;
mod HeeledBootIcon;
pub use HeeledBootIcon::*;
mod HighHeelIcon;
pub use HighHeelIcon::*;
mod HoodieIcon;
pub use HoodieIcon::*;
mod HotTubIcon;
pub use HotTubIcon::*;
mod Iron2Icon;
pub use Iron2Icon::*;
mod IronBanIcon;
pub use IronBanIcon::*;
mod IronIcon;
pub use IronIcon::*;
mod Jeans2Icon;
pub use Jeans2Icon::*;
mod JeansIcon;
pub use JeansIcon::*;
mod LegginsIcon;
pub use LegginsIcon::*;
mod LipGlossIcon;
pub use LipGlossIcon::*;
mod LipsIcon;
pub use LipsIcon::*;
mod Lipstick2Icon;
pub use Lipstick2Icon::*;
mod LipstickIcon;
pub use LipstickIcon::*;
mod MakeupBlushIcon;
pub use MakeupBlushIcon::*;
mod MakeupBrushIcon;
pub use MakeupBrushIcon::*;
mod MakeupCreamIcon;
pub use MakeupCreamIcon::*;
mod MakeupFoundationIcon;
pub use MakeupFoundationIcon::*;
mod MakeupIcon;
pub use MakeupIcon::*;
mod MakeupMirrorIcon;
pub use MakeupMirrorIcon::*;
mod MakeupPaletteIcon;
pub use MakeupPaletteIcon::*;
mod MascaraIcon;
pub use MascaraIcon::*;
mod MassageIcon;
pub use MassageIcon::*;
mod MortarAndPestleIcon;
pub use MortarAndPestleIcon::*;
mod MustacheIcon;
pub use MustacheIcon::*;
mod NailArtIcon;
pub use NailArtIcon::*;
mod NailFileIcon;
pub use NailFileIcon::*;
mod NailPolishIcon;
pub use NailPolishIcon::*;
mod NeckBrushIcon;
pub use NeckBrushIcon::*;
mod NeedleIcon;
pub use NeedleIcon::*;
mod PajamasIcon;
pub use PajamasIcon::*;
mod PerfumeIcon;
pub use PerfumeIcon::*;
mod PilgrimHatIcon;
pub use PilgrimHatIcon::*;
mod PipeIcon;
pub use PipeIcon::*;
mod PocketIcon;
pub use PocketIcon::*;
mod RazorIcon;
pub use RazorIcon::*;
mod RingIcon;
pub use RingIcon::*;
mod SaunaIcon;
pub use SaunaIcon::*;
mod ScarfIcon;
pub use ScarfIcon::*;
mod ScentedCandleIcon;
pub use ScentedCandleIcon::*;
mod Scissors2Icon;
pub use Scissors2Icon::*;
mod ScissorsCombIcon;
pub use ScissorsCombIcon::*;
mod Shirt2Icon;
pub use Shirt2Icon::*;
mod Shirt3Icon;
pub use Shirt3Icon::*;
mod Shirt4Icon;
pub use Shirt4Icon::*;
mod ShirtIcon;
pub use ShirtIcon::*;
mod ShoeIcon;
pub use ShoeIcon::*;
mod ShortsIcon;
pub use ShortsIcon::*;
mod SkirtIcon;
pub use SkirtIcon::*;
mod Slacks2Icon;
pub use Slacks2Icon::*;
mod SlacksIcon;
pub use SlacksIcon::*;
mod SlippersIcon;
pub use SlippersIcon::*;
mod SmartwatchIcon;
pub use SmartwatchIcon::*;
mod SneakerIcon;
pub use SneakerIcon::*;
mod SoapIcon;
pub use SoapIcon::*;
mod SockIcon;
pub use SockIcon::*;
mod SpaStonesIcon;
pub use SpaStonesIcon::*;
mod SportsBraIcon;
pub use SportsBraIcon::*;
mod SportsJerseyIcon;
pub use SportsJerseyIcon::*;
mod SportsTshirtIcon;
pub use SportsTshirtIcon::*;
mod StraightRazorIcon;
pub use StraightRazorIcon::*;
mod SuitIcon;
pub use SuitIcon::*;
mod SweaterIcon;
pub use SweaterIcon::*;
mod SwimsuitIcon;
pub use SwimsuitIcon::*;
mod TopHat2Icon;
pub use TopHat2Icon::*;
mod TowelIcon;
pub use TowelIcon::*;
mod TowelRackIcon;
pub use TowelRackIcon::*;
mod TowelWrappedHairIcon;
pub use TowelWrappedHairIcon::*;
mod Tshirt2Icon;
pub use Tshirt2Icon::*;
mod TshirtIcon;
pub use TshirtIcon::*;
mod Underwear2Icon;
pub use Underwear2Icon::*;
mod UnderwearIcon;
pub use UnderwearIcon::*;
mod VanityMirrorIcon;
pub use VanityMirrorIcon::*;
mod VestIcon;
pub use VestIcon::*;
mod Wash30Icon;
pub use Wash30Icon::*;
mod Wash60Icon;
pub use Wash60Icon::*;
mod Wash90Icon;
pub use Wash90Icon::*;
mod WashingMachineWaterIcon;
pub use WashingMachineWaterIcon::*;
mod Watch2Icon;
pub use Watch2Icon::*;
mod WatchIcon;
pub use WatchIcon::*;
mod WinterHatIcon;
pub use WinterHatIcon::*;
mod YogaIcon;
pub use YogaIcon::*;
