#![allow(non_snake_case)]

mod AdjustContrastIcon;
pub use AdjustContrastIcon::*;
mod AdultContentIcon;
pub use AdultContentIcon::*;
mod AntiShakeIcon;
pub use AntiShakeIcon::*;
mod ApertureIcon;
pub use ApertureIcon::*;
mod BoltAutoIcon;
pub use BoltAutoIcon::*;
mod BoltBanIcon;
pub use BoltBanIcon::*;
mod BoltIcon;
pub use BoltIcon::*;
mod BoltLightningAutoIcon;
pub use BoltLightningAutoIcon::*;
mod BoltLightningBanIcon;
pub use BoltLightningBanIcon::*;
mod BoltLightningIcon;
pub use BoltLightningIcon::*;
mod BoltSpeedIcon;
pub use BoltSpeedIcon::*;
mod BrightnessDecreaseIcon;
pub use BrightnessDecreaseIcon::*;
mod BrightnessIcon;
pub use BrightnessIcon::*;
mod BrightnessIncreaseIcon;
pub use BrightnessIncreaseIcon::*;
mod Camera2Icon;
pub use Camera2Icon::*;
mod Camera3Icon;
pub use Camera3Icon::*;
mod Camera4Icon;
pub use Camera4Icon::*;
mod CameraAutoIcon;
pub use CameraAutoIcon::*;
mod CameraBanIcon;
pub use CameraBanIcon::*;
mod CameraClockIcon;
pub use CameraClockIcon::*;
mod CameraFlashlightIcon;
pub use CameraFlashlightIcon::*;
mod CameraFocus2Icon;
pub use CameraFocus2Icon::*;
mod CameraFocus3Icon;
pub use CameraFocus3Icon::*;
mod CameraFocusIcon;
pub use CameraFocusIcon::*;
mod CameraGridIcon;
pub use CameraGridIcon::*;
mod CameraHeartIcon;
pub use CameraHeartIcon::*;
mod CameraIcon;
pub use CameraIcon::*;
mod CameraLensIcon;
pub use CameraLensIcon::*;
mod CameraRecordingIcon;
pub use CameraRecordingIcon::*;
mod CameraRollIcon;
pub use CameraRollIcon::*;
mod CameraRotateIcon;
pub use CameraRotateIcon::*;
mod CameraScreenIcon;
pub use CameraScreenIcon::*;
mod CameraSlashIcon;
pub use CameraSlashIcon::*;
mod CameraXmarkIcon;
pub use CameraXmarkIcon::*;
mod CircleMediaPauseIcon;
pub use CircleMediaPauseIcon::*;
mod CircleMediaPlayIcon;
pub use CircleMediaPlayIcon::*;
mod CircleMediaStopIcon;
pub use CircleMediaStopIcon::*;
mod CircleUserSparkle2Icon;
pub use CircleUserSparkle2Icon::*;
mod Circles5Icon;
pub use Circles5Icon::*;
mod ClapperboardIcon;
pub use ClapperboardIcon::*;
mod ClapperboardPlayIcon;
pub use ClapperboardPlayIcon::*;
mod CloudStreamingIcon;
pub use CloudStreamingIcon::*;
mod ContrastIcon;
pub use ContrastIcon::*;
mod Film2Icon;
pub use Film2Icon::*;
mod FilmHeartIcon;
pub use FilmHeartIcon::*;
mod FilmIcon;
pub use FilmIcon::*;
mod FilmPlayIcon;
pub use FilmPlayIcon::*;
mod Focus2Icon;
pub use Focus2Icon::*;
mod FrameEffectIcon;
pub use FrameEffectIcon::*;
mod Glasses3dIcon;
pub use Glasses3dIcon::*;
mod HalfDottedCircleOneIcon;
pub use HalfDottedCircleOneIcon::*;
mod HdmiIcon;
pub use HdmiIcon::*;
mod Image2Icon;
pub use Image2Icon::*;
mod Image3Icon;
pub use Image3Icon::*;
mod ImageIcon;
pub use ImageIcon::*;
mod ImageMinusIcon;
pub use ImageMinusIcon::*;
mod ImagePlusIcon;
pub use ImagePlusIcon::*;
mod ImagesIcon;
pub use ImagesIcon::*;
mod LaptopPlayIcon;
pub use LaptopPlayIcon::*;
mod MediaEjectIcon;
pub use MediaEjectIcon::*;
mod MediaLibraryIcon;
pub use MediaLibraryIcon::*;
mod MediaNextIcon;
pub use MediaNextIcon::*;
mod MediaPauseIcon;
pub use MediaPauseIcon::*;
mod MediaPlayIcon;
pub use MediaPlayIcon::*;
mod MediaPreviousIcon;
pub use MediaPreviousIcon::*;
mod MediaRecordIcon;
pub use MediaRecordIcon::*;
mod MediaSkipToEndIcon;
pub use MediaSkipToEndIcon::*;
mod MediaSkipToStartIcon;
pub use MediaSkipToStartIcon::*;
mod MediaStopIcon;
pub use MediaStopIcon::*;
mod MoonStars2Icon;
pub use MoonStars2Icon::*;
mod MovieReelIcon;
pub use MovieReelIcon::*;
mod PhoneCameraBackIcon;
pub use PhoneCameraBackIcon::*;
mod PhotoFrameHangIcon;
pub use PhotoFrameHangIcon::*;
mod PhotosIcon;
pub use PhotosIcon::*;
mod PictureIcon;
pub use PictureIcon::*;
mod PlaylistIcon;
pub use PlaylistIcon::*;
mod PolaroidIcon;
pub use PolaroidIcon::*;
mod PolaroidMinusIcon;
pub use PolaroidMinusIcon::*;
mod PolaroidPhotoIcon;
pub use PolaroidPhotoIcon::*;
mod PolaroidPlusIcon;
pub use PolaroidPlusIcon::*;
mod PolaroidPortraitIcon;
pub use PolaroidPortraitIcon::*;
mod PolaroidShotsIcon;
pub use PolaroidShotsIcon::*;
mod PowerOffIcon;
pub use PowerOffIcon::*;
mod ProgressBarIcon;
pub use ProgressBarIcon::*;
mod ProjectorIcon;
pub use ProjectorIcon::*;
mod QueueIcon;
pub use QueueIcon::*;
mod ScreenTouchIcon;
pub use ScreenTouchIcon::*;
mod SdCardIcon;
pub use SdCardIcon::*;
mod Selfie2Icon;
pub use Selfie2Icon::*;
mod SelfieIcon;
pub use SelfieIcon::*;
mod SportModeIcon;
pub use SportModeIcon::*;
mod SquarePlayIcon;
pub use SquarePlayIcon::*;
mod SquareStreamingIcon;
pub use SquareStreamingIcon::*;
mod SquareUserSparkle2Icon;
pub use SquareUserSparkle2Icon::*;
mod SubtitlesIcon;
pub use SubtitlesIcon::*;
mod TakeSelfieIcon;
pub use TakeSelfieIcon::*;
mod TapeIcon;
pub use TapeIcon::*;
mod TextToImage2Icon;
pub use TextToImage2Icon::*;
mod TextToImageIcon;
pub use TextToImageIcon::*;
mod Ticket2Icon;
pub use Ticket2Icon::*;
mod TicketIcon;
pub use TicketIcon::*;
mod Timer2Icon;
pub use Timer2Icon::*;
mod Timer3Icon;
pub use Timer3Icon::*;
mod TripodIcon;
pub use TripodIcon::*;
mod UserFocus2Icon;
pub use UserFocus2Icon::*;
mod UserFocusIcon;
pub use UserFocusIcon::*;
mod VibranceIcon;
pub use VibranceIcon::*;
mod Video2Icon;
pub use Video2Icon::*;
mod Video3Icon;
pub use Video3Icon::*;
mod VideoIcon;
pub use VideoIcon::*;
mod VideoOffIcon;
pub use VideoOffIcon::*;
mod VideoPlayIcon;
pub use VideoPlayIcon::*;
mod VideoPlayerIcon;
pub use VideoPlayerIcon::*;
mod VideoPlaylistIcon;
pub use VideoPlaylistIcon::*;
mod VignetteIcon;
pub use VignetteIcon::*;
mod Webcam2Icon;
pub use Webcam2Icon::*;
mod WebcamIcon;
pub use WebcamIcon::*;
mod WhiteBalanceIcon;
pub use WhiteBalanceIcon::*;
