#![allow(non_snake_case)]

mod AmpersandIcon;
pub use AmpersandIcon::*;
mod AtSign2Icon;
pub use AtSign2Icon::*;
mod BahaiIcon;
pub use BahaiIcon::*;
mod BuddhismIcon;
pub use BuddhismIcon::*;
mod ChristianityIcon;
pub use ChristianityIcon::*;
mod DruidismIcon;
pub use DruidismIcon::*;
mod GunBanIcon;
pub use GunBanIcon::*;
mod HinduismIcon;
pub use HinduismIcon::*;
mod IslamIcon;
pub use IslamIcon::*;
mod JudaismIcon;
pub use JudaismIcon::*;
mod LetterAIcon;
pub use LetterAIcon::*;
mod LetterBIcon;
pub use LetterBIcon::*;
mod LetterCIcon;
pub use LetterCIcon::*;
mod LetterDIcon;
pub use LetterDIcon::*;
mod LetterEIcon;
pub use LetterEIcon::*;
mod LetterFIcon;
pub use LetterFIcon::*;
mod LetterGIcon;
pub use LetterGIcon::*;
mod LetterHIcon;
pub use LetterHIcon::*;
mod LetterIIcon;
pub use LetterIIcon::*;
mod LetterJIcon;
pub use LetterJIcon::*;
mod LetterKIcon;
pub use LetterKIcon::*;
mod LetterLIcon;
pub use LetterLIcon::*;
mod LetterMIcon;
pub use LetterMIcon::*;
mod LetterNIcon;
pub use LetterNIcon::*;
mod LetterOIcon;
pub use LetterOIcon::*;
mod LetterPIcon;
pub use LetterPIcon::*;
mod LetterQIcon;
pub use LetterQIcon::*;
mod LetterRIcon;
pub use LetterRIcon::*;
mod LetterSIcon;
pub use LetterSIcon::*;
mod LetterTIcon;
pub use LetterTIcon::*;
mod LetterUIcon;
pub use LetterUIcon::*;
mod LetterVIcon;
pub use LetterVIcon::*;
mod LetterWIcon;
pub use LetterWIcon::*;
mod LetterXIcon;
pub use LetterXIcon::*;
mod LetterYIcon;
pub use LetterYIcon::*;
mod LetterZIcon;
pub use LetterZIcon::*;
mod NumberEightIcon;
pub use NumberEightIcon::*;
mod NumberFiveIcon;
pub use NumberFiveIcon::*;
mod NumberFourIcon;
pub use NumberFourIcon::*;
mod NumberNineIcon;
pub use NumberNineIcon::*;
mod NumberOneIcon;
pub use NumberOneIcon::*;
mod NumberSevenIcon;
pub use NumberSevenIcon::*;
mod NumberSixIcon;
pub use NumberSixIcon::*;
mod NumberThreeIcon;
pub use NumberThreeIcon::*;
mod NumberTwoIcon;
pub use NumberTwoIcon::*;
mod NumberZeroIcon;
pub use NumberZeroIcon::*;
mod TaoismIcon;
pub use TaoismIcon::*;
