#![allow(non_snake_case)]

mod AlienIcon;
pub use AlienIcon::*;
mod BombIcon;
pub use BombIcon::*;
mod CakeIcon;
pub use CakeIcon::*;
mod ClappingHandsIcon;
pub use ClappingHandsIcon::*;
mod FaceAngryIcon;
pub use FaceAngryIcon::*;
mod FaceAnimeIcon;
pub use FaceAnimeIcon::*;
mod FaceConfusedIcon;
pub use FaceConfusedIcon::*;
mod FaceCoolSunglasses2Icon;
pub use FaceCoolSunglasses2Icon::*;
mod FaceCoolSunglassesIcon;
pub use FaceCoolSunglassesIcon::*;
mod FaceCrossedOutEyesIcon;
pub use FaceCrossedOutEyesIcon::*;
mod FaceCryingOutIcon;
pub use FaceCryingOutIcon::*;
mod FaceCuteIcon;
pub use FaceCuteIcon::*;
mod FaceEvilIcon;
pub use FaceEvilIcon::*;
mod FaceGrimacingIcon;
pub use FaceGrimacingIcon::*;
mod FaceGrinIcon;
pub use FaceGrinIcon::*;
mod FaceGrinSquintIcon;
pub use FaceGrinSquintIcon::*;
mod FaceGrinWinkIcon;
pub use FaceGrinWinkIcon::*;
mod FaceKidCapIcon;
pub use FaceKidCapIcon::*;
mod FaceKissIcon;
pub use FaceKissIcon::*;
mod FaceLaughing2Icon;
pub use FaceLaughing2Icon::*;
mod FaceLaughingIcon;
pub use FaceLaughingIcon::*;
mod FaceLossForWordsIcon;
pub use FaceLossForWordsIcon::*;
mod FaceMaskIcon;
pub use FaceMaskIcon::*;
mod FaceMinusIcon;
pub use FaceMinusIcon::*;
mod FaceMonsterIcon;
pub use FaceMonsterIcon::*;
mod FaceMustacheIcon;
pub use FaceMustacheIcon::*;
mod FaceNauseatedIcon;
pub use FaceNauseatedIcon::*;
mod FaceNerdGrinIcon;
pub use FaceNerdGrinIcon::*;
mod FaceNerdIcon;
pub use FaceNerdIcon::*;
mod FaceNerdSmileIcon;
pub use FaceNerdSmileIcon::*;
mod FaceNeutralIcon;
pub use FaceNeutralIcon::*;
mod FaceNinjaIcon;
pub use FaceNinjaIcon::*;
mod FacePirateIcon;
pub use FacePirateIcon::*;
mod FacePlusIcon;
pub use FacePlusIcon::*;
mod FacePoutingIcon;
pub use FacePoutingIcon::*;
mod FaceRobotIcon;
pub use FaceRobotIcon::*;
mod FaceRockerIcon;
pub use FaceRockerIcon::*;
mod FaceSadCryingIcon;
pub use FaceSadCryingIcon::*;
mod FaceSadIcon;
pub use FaceSadIcon::*;
mod FaceSearchIcon;
pub use FaceSearchIcon::*;
mod FaceSkepticalIcon;
pub use FaceSkepticalIcon::*;
mod FaceSleepingIcon;
pub use FaceSleepingIcon::*;
mod FaceSleepyIcon;
pub use FaceSleepyIcon::*;
mod FaceSmileClosedEyesIcon;
pub use FaceSmileClosedEyesIcon::*;
mod FaceSmileIcon;
pub use FaceSmileIcon::*;
mod FaceSmileWinkIcon;
pub use FaceSmileWinkIcon::*;
mod FaceSmirkingGrinIcon;
pub use FaceSmirkingGrinIcon::*;
mod FaceSmirkingIcon;
pub use FaceSmirkingIcon::*;
mod FaceSmirkingSquintIcon;
pub use FaceSmirkingSquintIcon::*;
mod FaceSoldierIcon;
pub use FaceSoldierIcon::*;
mod FaceSunIcon;
pub use FaceSunIcon::*;
mod FaceSurpriseIcon;
pub use FaceSurpriseIcon::*;
mod FaceSurprisedIcon;
pub use FaceSurprisedIcon::*;
mod FaceTiredIcon;
pub use FaceTiredIcon::*;
mod FaceTongueClosedEyesIcon;
pub use FaceTongueClosedEyesIcon::*;
mod FaceTongueOutIcon;
pub use FaceTongueOutIcon::*;
mod FaceTongueWinkIcon;
pub use FaceTongueWinkIcon::*;
mod FaceUwuIcon;
pub use FaceUwuIcon::*;
mod FaceWoozyClosedEyesIcon;
pub use FaceWoozyClosedEyesIcon::*;
mod FaceWoozyIcon;
pub use FaceWoozyIcon::*;
mod FaceZipMouthIcon;
pub use FaceZipMouthIcon::*;
mod FistIcon;
pub use FistIcon::*;
mod GhostTongueOutIcon;
pub use GhostTongueOutIcon::*;
mod HandsPrayingIcon;
pub use HandsPrayingIcon::*;
mod HappyBaby2Icon;
pub use HappyBaby2Icon::*;
mod HappyBabyIcon;
pub use HappyBabyIcon::*;
mod HeartBrokenIcon;
pub use HeartBrokenIcon::*;
mod HighFiveIcon;
pub use HighFiveIcon::*;
mod PartyIcon;
pub use PartyIcon::*;
mod PileOfPooIcon;
pub use PileOfPooIcon::*;
mod SkullIcon;
pub use SkullIcon::*;
mod SleepBubbleIcon;
pub use SleepBubbleIcon::*;
mod SnappingFingersIcon;
pub use SnappingFingersIcon::*;
mod ThumbsDownIcon;
pub use ThumbsDownIcon::*;
mod ThumbsUp2Icon;
pub use ThumbsUp2Icon::*;
mod ThumbsUpIcon;
pub use ThumbsUpIcon::*;
mod TongueOutIcon;
pub use TongueOutIcon::*;
