#![allow(non_snake_case)]

mod AbcLettersIcon;
pub use AbcLettersIcon::*;
mod AwardMedalIcon;
pub use AwardMedalIcon::*;
mod Backpack3Icon;
pub use Backpack3Icon::*;
mod Backpack4Icon;
pub use Backpack4Icon::*;
mod BasketballIcon;
pub use BasketballIcon::*;
mod Bell2Icon;
pub use Bell2Icon::*;
mod BookBookmark2Icon;
pub use BookBookmark2Icon::*;
mod BookIcon;
pub use BookIcon::*;
mod BookOpen2Icon;
pub use BookOpen2Icon::*;
mod BookOpen3Icon;
pub use BookOpen3Icon::*;
mod BookOpenIcon;
pub use BookOpenIcon::*;
mod Books2Icon;
pub use Books2Icon::*;
mod Bus2Icon;
pub use Bus2Icon::*;
mod BusShuttleIcon;
pub use BusShuttleIcon::*;
mod BusSideIcon;
pub use BusSideIcon::*;
mod ChalkboardIcon;
pub use ChalkboardIcon::*;
mod ClipboardNotesIcon;
pub use ClipboardNotesIcon::*;
mod DocumentSearchIcon;
pub use DocumentSearchIcon::*;
mod EquationIcon;
pub use EquationIcon::*;
mod Glasses2Icon;
pub use Glasses2Icon::*;
mod Globe2Icon;
pub use Globe2Icon::*;
mod GraduationCapIcon;
pub use GraduationCapIcon::*;
mod GraduationCertificateIcon;
pub use GraduationCertificateIcon::*;
mod Highlighter2Icon;
pub use Highlighter2Icon::*;
mod HighlighterIcon;
pub use HighlighterIcon::*;
mod Language2Icon;
pub use Language2Icon::*;
mod NewtonsCradleIcon;
pub use NewtonsCradleIcon::*;
mod NotepadIcon;
pub use NotepadIcon::*;
mod NumbersIcon;
pub use NumbersIcon::*;
mod Pen3Icon;
pub use Pen3Icon::*;
mod Pen4Icon;
pub use Pen4Icon::*;
mod Pencil2Icon;
pub use Pencil2Icon::*;
mod PersonReadingIcon;
pub use PersonReadingIcon::*;
mod PlanetIcon;
pub use PlanetIcon::*;
mod PresentationScreen2Icon;
pub use PresentationScreen2Icon::*;
mod SchoolBuildingIcon;
pub use SchoolBuildingIcon::*;
mod SoccerBallIcon;
pub use SoccerBallIcon::*;
mod TelescopeIcon;
pub use TelescopeIcon::*;
mod TelescopeTripodIcon;
pub use TelescopeTripodIcon::*;
mod TextHighlight2Icon;
pub use TextHighlight2Icon::*;
mod TextHighlightIcon;
pub use TextHighlightIcon::*;
mod TextbookIcon;
pub use TextbookIcon::*;
mod UserBookOpenIcon;
pub use UserBookOpenIcon::*;
