#![allow(non_snake_case)]

mod AddAboveIcon;
pub use AddAboveIcon::*;
mod AddBelowIcon;
pub use AddBelowIcon::*;
mod AddItemIcon;
pub use AddItemIcon::*;
mod AdjustContrast2Icon;
pub use AdjustContrast2Icon::*;
mod AdjustContrast3Icon;
pub use AdjustContrast3Icon::*;
mod AlbumIcon;
pub use AlbumIcon::*;
mod AlignBottomIcon;
pub use AlignBottomIcon::*;
mod AlignHorizontalIcon;
pub use AlignHorizontalIcon::*;
mod AlignLeftIcon;
pub use AlignLeftIcon::*;
mod AlignRightIcon;
pub use AlignRightIcon::*;
mod AlignTopIcon;
pub use AlignTopIcon::*;
mod AlignVerticalIcon;
pub use AlignVerticalIcon::*;
mod AngleIcon;
pub use AngleIcon::*;
mod AnimationBounceIcon;
pub use AnimationBounceIcon::*;
mod AnimationFramesIcon;
pub use AnimationFramesIcon::*;
mod AnimationIcon;
pub use AnimationIcon::*;
mod ApiIcon;
pub use ApiIcon::*;
mod ApplicationsIcon;
pub use ApplicationsIcon::*;
mod BinaryIcon;
pub use BinaryIcon::*;
mod BooleanExcludeIcon;
pub use BooleanExcludeIcon::*;
mod BooleanIntersectIcon;
pub use BooleanIntersectIcon::*;
mod BooleanSubtractIcon;
pub use BooleanSubtractIcon::*;
mod BooleanUnionIcon;
pub use BooleanUnionIcon::*;
mod BorderRadiusIcon;
pub use BorderRadiusIcon::*;
mod BorderWidthIcon;
pub use BorderWidthIcon::*;
mod Broom2Icon;
pub use Broom2Icon::*;
mod BroomSparkleIcon;
pub use BroomSparkleIcon::*;
mod BucketIcon;
pub use BucketIcon::*;
mod BucketPaint2Icon;
pub use BucketPaint2Icon::*;
mod BucketPaintIcon;
pub use BucketPaintIcon::*;
mod Button2Icon;
pub use Button2Icon::*;
mod CanvasIcon;
pub use CanvasIcon::*;
mod CardsIcon;
pub use CardsIcon::*;
mod ClearTextFormattingIcon;
pub use ClearTextFormattingIcon::*;
mod ClothPatchIcon;
pub use ClothPatchIcon::*;
mod CodeCommitIcon;
pub use CodeCommitIcon::*;
mod CodeEditorIcon;
pub use CodeEditorIcon::*;
mod CodeIcon;
pub use CodeIcon::*;
mod ColorPaletteIcon;
pub use ColorPaletteIcon::*;
mod CommandIcon;
pub use CommandIcon::*;
mod CompareItemsIcon;
pub use CompareItemsIcon::*;
mod Connections2Icon;
pub use Connections2Icon::*;
mod ConnectionsIcon;
pub use ConnectionsIcon::*;
mod ConsoleIcon;
pub use ConsoleIcon::*;
mod CopyIcon;
pub use CopyIcon::*;
mod CropIcon;
pub use CropIcon::*;
mod Css3Icon;
pub use Css3Icon::*;
mod CubeAxisIcon;
pub use CubeAxisIcon::*;
mod CubeIcon;
pub use CubeIcon::*;
mod Cursor2Icon;
pub use Cursor2Icon::*;
mod CursorAddIcon;
pub use CursorAddIcon::*;
mod CursorGrabIcon;
pub use CursorGrabIcon::*;
mod CursorIcon;
pub use CursorIcon::*;
mod CursorLoadIcon;
pub use CursorLoadIcon::*;
mod CursorMenuIcon;
pub use CursorMenuIcon::*;
mod CursorNotAllowedIcon;
pub use CursorNotAllowedIcon::*;
mod CursorPointerIcon;
pub use CursorPointerIcon::*;
mod CurveIcon;
pub use CurveIcon::*;
mod DarkModeIcon;
pub use DarkModeIcon::*;
mod DatabaseIcon;
pub use DatabaseIcon::*;
mod DesignDevIcon;
pub use DesignDevIcon::*;
mod DrawCompassIcon;
pub use DrawCompassIcon::*;
mod DrawingTabletIcon;
pub use DrawingTabletIcon::*;
mod DropCapIcon;
pub use DropCapIcon::*;
mod EditCircleIcon;
pub use EditCircleIcon::*;
mod EditPolygonIcon;
pub use EditPolygonIcon::*;
mod EditSquareIcon;
pub use EditSquareIcon::*;
mod EditTriangleIcon;
pub use EditTriangleIcon::*;
mod Eraser2Icon;
pub use Eraser2Icon::*;
mod Eraser3Icon;
pub use Eraser3Icon::*;
mod EraserIcon;
pub use EraserIcon::*;
mod EyeClosedIcon;
pub use EyeClosedIcon::*;
mod EyeDropperIcon;
pub use EyeDropperIcon::*;
mod EyeOpenIcon;
pub use EyeOpenIcon::*;
mod FileAiIcon;
pub use FileAiIcon::*;
mod FileAseIcon;
pub use FileAseIcon::*;
mod FileAspIcon;
pub use FileAspIcon::*;
mod FileAspxIcon;
pub use FileAspxIcon::*;
mod FileCPlusPlusIcon;
pub use FileCPlusPlusIcon::*;
mod FileCadIcon;
pub use FileCadIcon::*;
mod FileCfmIcon;
pub use FileCfmIcon::*;
mod FileCgiIcon;
pub use FileCgiIcon::*;
mod FileCodeIcon;
pub use FileCodeIcon::*;
mod FileCshIcon;
pub use FileCshIcon::*;
mod FileCssIcon;
pub use FileCssIcon::*;
mod FileEpsIcon;
pub use FileEpsIcon::*;
mod FileFigIcon;
pub use FileFigIcon::*;
mod FileFontIcon;
pub use FileFontIcon::*;
mod FileGifIcon;
pub use FileGifIcon::*;
mod FileGzipIcon;
pub use FileGzipIcon::*;
mod FileHtmlIcon;
pub use FileHtmlIcon::*;
mod FileJavaIcon;
pub use FileJavaIcon::*;
mod FileJpgIcon;
pub use FileJpgIcon::*;
mod FileJsIcon;
pub use FileJsIcon::*;
mod FileJsonIcon;
pub use FileJsonIcon::*;
mod FileJspIcon;
pub use FileJspIcon::*;
mod FileJsxIcon;
pub use FileJsxIcon::*;
mod FileLogIcon;
pub use FileLogIcon::*;
mod FileMaxIcon;
pub use FileMaxIcon::*;
mod FileMdIcon;
pub use FileMdIcon::*;
mod FileObjIcon;
pub use FileObjIcon::*;
mod FileOtfIcon;
pub use FileOtfIcon::*;
mod FilePdfIcon;
pub use FilePdfIcon::*;
mod FilePhpIcon;
pub use FilePhpIcon::*;
mod FilePngIcon;
pub use FilePngIcon::*;
mod FilePsdIcon;
pub use FilePsdIcon::*;
mod FilePyIcon;
pub use FilePyIcon::*;
mod FileRawIcon;
pub use FileRawIcon::*;
mod FileRubyIcon;
pub use FileRubyIcon::*;
mod FileSqlIcon;
pub use FileSqlIcon::*;
mod FileSvgIcon;
pub use FileSvgIcon::*;
mod FileTifIcon;
pub use FileTifIcon::*;
mod FileTiffIcon;
pub use FileTiffIcon::*;
mod FileTreeIcon;
pub use FileTreeIcon::*;
mod FileTsIcon;
pub use FileTsIcon::*;
mod FileTsxIcon;
pub use FileTsxIcon::*;
mod FileTtfIcon;
pub use FileTtfIcon::*;
mod FileWebpIcon;
pub use FileWebpIcon::*;
mod FileWoffIcon;
pub use FileWoffIcon::*;
mod FileXmlIcon;
pub use FileXmlIcon::*;
mod FillIcon;
pub use FillIcon::*;
mod FlipHorizontalIcon;
pub use FlipHorizontalIcon::*;
mod FlipVerticalIcon;
pub use FlipVerticalIcon::*;
mod FocusModeIcon;
pub use FocusModeIcon::*;
mod FolderDevIcon;
pub use FolderDevIcon::*;
mod FrameIcon;
pub use FrameIcon::*;
mod FunctionIcon;
pub use FunctionIcon::*;
mod GradientIcon;
pub use GradientIcon::*;
mod GrainEffectIcon;
pub use GrainEffectIcon::*;
mod GridCircleIcon;
pub use GridCircleIcon::*;
mod GridPlus2Icon;
pub use GridPlus2Icon::*;
mod GridSystemIcon;
pub use GridSystemIcon::*;
mod Heading1Icon;
pub use Heading1Icon::*;
mod Heading2Icon;
pub use Heading2Icon::*;
mod Heading3Icon;
pub use Heading3Icon::*;
mod Heading4Icon;
pub use Heading4Icon::*;
mod Heading5Icon;
pub use Heading5Icon::*;
mod Heading6Icon;
pub use Heading6Icon::*;
mod HotspotIcon;
pub use HotspotIcon::*;
mod Html5Icon;
pub use Html5Icon::*;
mod ImageBinaryIcon;
pub use ImageBinaryIcon::*;
mod ImageSparkleIcon;
pub use ImageSparkleIcon::*;
mod IndentDecrease2Icon;
pub use IndentDecrease2Icon::*;
mod IndentDecreaseIcon;
pub use IndentDecreaseIcon::*;
mod IndentIncrease2Icon;
pub use IndentIncrease2Icon::*;
mod IndentIncreaseIcon;
pub use IndentIncreaseIcon::*;
mod JsonLogoIcon;
pub use JsonLogoIcon::*;
mod LaptopAiGeneratedIcon;
pub use LaptopAiGeneratedIcon::*;
mod LaptopAppsIcon;
pub use LaptopAppsIcon::*;
mod LaptopCodeIcon;
pub use LaptopCodeIcon::*;
mod LaptopDev2Icon;
pub use LaptopDev2Icon::*;
mod LaptopDevIcon;
pub use LaptopDevIcon::*;
mod LaptopDownloadIcon;
pub use LaptopDownloadIcon::*;
mod LaptopIcon;
pub use LaptopIcon::*;
mod LaptopMobileIcon;
pub use LaptopMobileIcon::*;
mod Layers2Icon;
pub use Layers2Icon::*;
mod LayersIcon;
pub use LayersIcon::*;
mod LayersStackedIcon;
pub use LayersStackedIcon::*;
mod LetterSpacingIcon;
pub use LetterSpacingIcon::*;
mod LevelsIcon;
pub use LevelsIcon::*;
mod LineHeightIcon;
pub use LineHeightIcon::*;
mod LineSpacingIcon;
pub use LineSpacingIcon::*;
mod ListTreeIcon;
pub use ListTreeIcon::*;
mod LockPasswordIcon;
pub use LockPasswordIcon::*;
mod MagicWandSparkleIcon;
pub use MagicWandSparkleIcon::*;
mod MagnetIcon;
pub use MagnetIcon::*;
mod MarkdownIcon;
pub use MarkdownIcon::*;
mod MaskOvalIcon;
pub use MaskOvalIcon::*;
mod MaskRectIcon;
pub use MaskRectIcon::*;
mod MobileCastingIcon;
pub use MobileCastingIcon::*;
mod MobileCodeIcon;
pub use MobileCodeIcon::*;
mod MobileDesignIcon;
pub use MobileDesignIcon::*;
mod MobileIcon;
pub use MobileIcon::*;
mod Monitor2Icon;
pub use Monitor2Icon::*;
mod MonitorIcon;
pub use MonitorIcon::*;
mod MonitorMobileIcon;
pub use MonitorMobileIcon::*;
mod Mouse2Icon;
pub use Mouse2Icon::*;
mod Mouse3Icon;
pub use Mouse3Icon::*;
mod MouseIcon;
pub use MouseIcon::*;
mod NewsletterCodeIcon;
pub use NewsletterCodeIcon::*;
mod NoteCodeIcon;
pub use NoteCodeIcon::*;
mod NotificationIcon;
pub use NotificationIcon::*;
mod NotificationPlusIcon;
pub use NotificationPlusIcon::*;
mod ObjsGroupIcon;
pub use ObjsGroupIcon::*;
mod ObjsUngroupIcon;
pub use ObjsUngroupIcon::*;
mod PaintRollerIcon;
pub use PaintRollerIcon::*;
mod Paintbrush2Icon;
pub use Paintbrush2Icon::*;
mod Paintbrush3Icon;
pub use Paintbrush3Icon::*;
mod Paintbrush4Icon;
pub use Paintbrush4Icon::*;
mod PaintbrushIcon;
pub use PaintbrushIcon::*;
mod PaletteIcon;
pub use PaletteIcon::*;
mod ParagraphSpacingIcon;
pub use ParagraphSpacingIcon::*;
mod Patch2Icon;
pub use Patch2Icon::*;
mod PenNib2Icon;
pub use PenNib2Icon::*;
mod PenNibIcon;
pub use PenNibIcon::*;
mod PencilIcon;
pub use PencilIcon::*;
mod PhoneAppsIcon;
pub use PhoneAppsIcon::*;
mod PhotoAlbumIcon;
pub use PhotoAlbumIcon::*;
mod PhotoEditorIcon;
pub use PhotoEditorIcon::*;
mod PhotoFrameIcon;
pub use PhotoFrameIcon::*;
mod Plug2Icon;
pub use Plug2Icon::*;
mod PlugIcon;
pub use PlugIcon::*;
mod PositionIcon;
pub use PositionIcon::*;
mod PriorityHighIcon;
pub use PriorityHighIcon::*;
mod PriorityHighestIcon;
pub use PriorityHighestIcon::*;
mod PriorityLowIcon;
pub use PriorityLowIcon::*;
mod PriorityLowestIcon;
pub use PriorityLowestIcon::*;
mod PriorityNormalIcon;
pub use PriorityNormalIcon::*;
mod PrototypeIcon;
pub use PrototypeIcon::*;
mod PyramidIcon;
pub use PyramidIcon::*;
mod RectLayoutGrid3Icon;
pub use RectLayoutGrid3Icon::*;
mod RenameIcon;
pub use RenameIcon::*;
mod Ruler2Icon;
pub use Ruler2Icon::*;
mod RulerArrowIcon;
pub use RulerArrowIcon::*;
mod RulerIcon;
pub use RulerIcon::*;
mod RulerPen2Icon;
pub use RulerPen2Icon::*;
mod RulerPenIcon;
pub use RulerPenIcon::*;
mod RulerTriangleIcon;
pub use RulerTriangleIcon::*;
mod ScissorsDashedIcon;
pub use ScissorsDashedIcon::*;
mod ScissorsIcon;
pub use ScissorsIcon::*;
mod ScribbleIcon;
pub use ScribbleIcon::*;
mod ScrollDevIcon;
pub use ScrollDevIcon::*;
mod ScrollPaintbrushIcon;
pub use ScrollPaintbrushIcon::*;
mod SelectAreaIcon;
pub use SelectAreaIcon::*;
mod Server2Icon;
pub use Server2Icon::*;
mod ServerIcon;
pub use ServerIcon::*;
mod ShapeAdjustIcon;
pub use ShapeAdjustIcon::*;
mod ShapeArrowIcon;
pub use ShapeArrowIcon::*;
mod ShapeCustomIcon;
pub use ShapeCustomIcon::*;
mod ShapeLineIcon;
pub use ShapeLineIcon::*;
mod ShapeOvalIcon;
pub use ShapeOvalIcon::*;
mod ShapePolygon2Icon;
pub use ShapePolygon2Icon::*;
mod ShapeRectangleIcon;
pub use ShapeRectangleIcon::*;
mod ShapeStarIcon;
pub use ShapeStarIcon::*;
mod ShapeTriangle2Icon;
pub use ShapeTriangle2Icon::*;
mod Shapes2Icon;
pub use Shapes2Icon::*;
mod ShapesIcon;
pub use ShapesIcon::*;
mod SharpenerIcon;
pub use SharpenerIcon::*;
mod SidebarRightIcon;
pub use SidebarRightIcon::*;
mod SizeLgIcon;
pub use SizeLgIcon::*;
mod SizeMdIcon;
pub use SizeMdIcon::*;
mod SizeSmIcon;
pub use SizeSmIcon::*;
mod SliceIcon;
pub use SliceIcon::*;
mod Sparkle3Icon;
pub use Sparkle3Icon::*;
mod SparkleIcon;
pub use SparkleIcon::*;
mod SphereIcon;
pub use SphereIcon::*;
mod SprayCanIcon;
pub use SprayCanIcon::*;
mod SquareCommandIcon;
pub use SquareCommandIcon::*;
mod SquarePaintbrushIcon;
pub use SquarePaintbrushIcon::*;
mod SquaresConnectedIcon;
pub use SquaresConnectedIcon::*;
mod StampIcon;
pub use StampIcon::*;
mod StickerIcon;
pub use StickerIcon::*;
mod TabletMobile2Icon;
pub use TabletMobile2Icon::*;
mod TabletMobileIcon;
pub use TabletMobileIcon::*;
mod TextAlignCenterIcon;
pub use TextAlignCenterIcon::*;
mod TextAlignJustifyIcon;
pub use TextAlignJustifyIcon::*;
mod TextAlignLeftIcon;
pub use TextAlignLeftIcon::*;
mod TextAlignRightIcon;
pub use TextAlignRightIcon::*;
mod TextAreaIcon;
pub use TextAreaIcon::*;
mod TextBgColorIcon;
pub use TextBgColorIcon::*;
mod TextColor2Icon;
pub use TextColor2Icon::*;
mod TextColorIcon;
pub use TextColorIcon::*;
mod TextCursorIcon;
pub use TextCursorIcon::*;
mod TextIcon;
pub use TextIcon::*;
mod TextItalicIcon;
pub use TextItalicIcon::*;
mod TextLowercaseIcon;
pub use TextLowercaseIcon::*;
mod TextOverlineIcon;
pub use TextOverlineIcon::*;
mod TextScaleXIcon;
pub use TextScaleXIcon::*;
mod TextSizeChangeIcon;
pub use TextSizeChangeIcon::*;
mod TextSizeDecreaseIcon;
pub use TextSizeDecreaseIcon::*;
mod TextSizeDownIcon;
pub use TextSizeDownIcon::*;
mod TextSizeIcon;
pub use TextSizeIcon::*;
mod TextSizeIncreaseIcon;
pub use TextSizeIncreaseIcon::*;
mod TextSparkleIcon;
pub use TextSparkleIcon::*;
mod TextStrikethroughIcon;
pub use TextStrikethroughIcon::*;
mod TextTitleCaseIcon;
pub use TextTitleCaseIcon::*;
mod TextTool2Icon;
pub use TextTool2Icon::*;
mod TextTool3Icon;
pub use TextTool3Icon::*;
mod TextToolIcon;
pub use TextToolIcon::*;
mod TextTrackingIcon;
pub use TextTrackingIcon::*;
mod TextUnderlineIcon;
pub use TextUnderlineIcon::*;
mod TextUppercaseIcon;
pub use TextUppercaseIcon::*;
mod TextureIcon;
pub use TextureIcon::*;
mod TodoIcon;
pub use TodoIcon::*;
mod ToolBlurIcon;
pub use ToolBlurIcon::*;
mod ToolHandIcon;
pub use ToolHandIcon::*;
mod ToolMeshIcon;
pub use ToolMeshIcon::*;
mod ToolSelectIcon;
pub use ToolSelectIcon::*;
mod Transform2dIcon;
pub use Transform2dIcon::*;
mod TransformIcon;
pub use TransformIcon::*;
mod TransformOriginIcon;
pub use TransformOriginIcon::*;
mod TransparentIcon;
pub use TransparentIcon::*;
mod TypeScaleIcon;
pub use TypeScaleIcon::*;
mod TypographyIcon;
pub use TypographyIcon::*;
mod UsbIcon;
pub use UsbIcon::*;
mod UserLaptopIcon;
pub use UserLaptopIcon::*;
mod VectorIcon;
pub use VectorIcon::*;
mod WandIcon;
pub use WandIcon::*;
mod WandSparkleIcon;
pub use WandSparkleIcon::*;
mod WatchCodeIcon;
pub use WatchCodeIcon::*;
mod WindowCodeIcon;
pub use WindowCodeIcon::*;
mod WindowCursorIcon;
pub use WindowCursorIcon::*;
mod WindowDevIcon;
pub use WindowDevIcon::*;
mod WindowIcon;
pub use WindowIcon::*;
mod WindowKeyIcon;
pub use WindowKeyIcon::*;
mod WindowLayoutIcon;
pub use WindowLayoutIcon::*;
mod WindowMinusIcon;
pub use WindowMinusIcon::*;
mod WindowPaintbrushIcon;
pub use WindowPaintbrushIcon::*;
mod WindowParagraphIcon;
pub use WindowParagraphIcon::*;
mod WindowPlusIcon;
pub use WindowPlusIcon::*;
mod WindowPointerIcon;
pub use WindowPointerIcon::*;
mod WindowResponsiveIcon;
pub use WindowResponsiveIcon::*;
