import type { BodyKindType, MethodType, RouteMetaType, TransportType } from "./types";

/**
 * The body a request carries.
 *
 * A `multipart` body cannot be a string: a `File` has to reach `FormData`
 * intact, which is what lets the framework rebuild it as a `RequestFile`.
 */
export type RequestBodyType =
  | { kind: "json"; text: string }
  | { kind: "multipart"; fields: Record<string, string>; files: Record<string, File> };

export const bodyKindOf = (meta: RouteMetaType): BodyKindType => meta.payload?.contentType ?? "json";

/** Everything the try-it form collected, ready to be put on the wire. */
export type RequestInputType = {
  /** Backend origin, e.g. `http://localhost:3000`. No trailing slash. */
  baseURL: string;
  meta: RouteMetaType;
  params: Record<string, string>;
  queries: Record<string, string>;
  headers: Record<string, string>;
  /** The body, in whichever shape the route's content type calls for. */
  body?: RequestBodyType;
  /** Forwarded as `Authorization: Bearer …` when present. */
  bearerToken?: string;
  signal?: AbortSignal;
  /** Called per chunk for `stream`, per event for `sse`. Never called for `http`. */
  onChunk?: (chunk: unknown) => void;
};

/** What came back, in the shape the response panel renders. */
export type RequestResultType = {
  status: number;
  statusText: string;
  /** Wall-clock time from send to last byte, in milliseconds. */
  duration: number;
  headers: Record<string, string>;
  /** Parsed JSON when the body is JSON, the raw text otherwise. */
  body: unknown;
  raw: string;
  ok: boolean;
};

/** A request the explorer refused to send, with the reason a reader can act on. */
export type RequestErrorType = {
  message: string;
  duration: number;
};

/** The verbs that carry a request body. */
const BODY_METHODS: readonly MethodType[] = ["post", "put", "patch"];

export const hasBody = (method: MethodType): boolean => BODY_METHODS.includes(method);

/**
 * Whether a route carries a request payload at all.
 *
 * A socket route does — in its message, not in an HTTP body — so asking the
 * verb alone would document it as taking nothing.
 */
export const carriesPayload = (meta: RouteMetaType): boolean => hasBody(meta.method) || transportOf(meta) === "socket";

export const transportOf = (meta: RouteMetaType): TransportType =>
  meta.transport ?? (meta.method === "socket" ? "socket" : "http");

/** Whether the route needs a bearer token before it will answer. */
export const isProtected = (meta: RouteMetaType): boolean => meta.roles.length > 0;

/**
 * Substitute the `:param` segments and append the non-empty queries. Values are
 * encoded, so a path parameter carrying a slash cannot invent a new segment.
 */
export const buildEndpoint = (
  template: string,
  params: Record<string, string> = {},
  queries: Record<string, string> = {},
): string => {
  const path = template.replace(/:(\w+)/g, (_, key: string) => encodeURIComponent(params[key] ?? ""));
  const search = new URLSearchParams(
    Object.entries(queries).filter(([, value]) => value !== undefined && value !== ""),
  ).toString();
  return search ? `${path}?${search}` : path;
};

export const buildUrl = (input: Pick<RequestInputType, "baseURL" | "meta" | "params" | "queries">): string =>
  `${input.baseURL.replace(/\/$/, "")}${buildEndpoint(input.meta.path, input.params, input.queries)}`;

/** The headers the request travels with, ours merged under the route's own. */
export const buildHeaders = (input: RequestInputType): Record<string, string> => {
  const headers: Record<string, string> = { ...input.headers };
  // A multipart body sets its own Content-Type: the boundary is generated by
  // `fetch`, and naming the type ourselves would omit it and break the parse.
  if (hasBody(input.meta.method) && input.body?.kind === "json" && input.body.text !== "") {
    headers["Content-Type"] = "application/json";
  }
  if (transportOf(input.meta) === "sse") {
    headers.Accept = "text/event-stream";
  }
  if (input.bearerToken) {
    headers.Authorization = `Bearer ${input.bearerToken}`;
  }
  return headers;
};

/** Parse a body as JSON, falling back to the raw text when it isn't. */
const readBody = (raw: string): unknown => {
  if (raw.trim() === "") {
    return undefined;
  }
  try {
    return JSON.parse(raw) as unknown;
  } catch {
    return raw;
  }
};

const collectHeaders = (headers: Headers): Record<string, string> => {
  const collected: Record<string, string> = {};
  headers.forEach((value, key) => {
    collected[key] = value;
  });
  return collected;
};

/**
 * Drain a streamed response body chunk by chunk, decoding the bytes and
 * handing the growing buffer to `extract` after each one so it can pull out
 * whatever frames are complete and return what is left unconsumed.
 *
 * `readStream` and `readEventStream` differ only in how a frame is delimited
 * and parsed — this carries the reading, decoding and abort handling once for
 * both.
 */
const drainStream = async (
  response: Response,
  signal: AbortSignal | undefined,
  extract: (buffer: string) => string,
): Promise<string> => {
  const body = response.body;
  if (!body) {
    return "";
  }

  const decoder = new TextDecoder();
  let buffer = "";
  let raw = "";

  const sink = new WritableStream<Uint8Array>({
    write: (value) => {
      const text = decoder.decode(value, { stream: true });
      raw += text;
      buffer = extract(buffer + text);
    },
  });

  try {
    // `pipeTo` carries the abort itself: it cancels the source and rejects.
    await body.pipeTo(sink, { signal });
  } catch (error) {
    // Aborting is how a reader stops a stream — hand back what already arrived.
    if (!signal?.aborted) {
      throw error;
    }
  }

  return raw;
};

/**
 * Read a newline-delimited stream, handing each line to `onChunk` as it lands
 * and keeping the whole body for the response panel.
 */
const readStream = (
  response: Response,
  onChunk: ((chunk: unknown) => void) | undefined,
  signal: AbortSignal | undefined,
): Promise<string> =>
  drainStream(response, signal, (buffer) => {
    // Split once: the last piece is whatever follows the final newline, and is
    // held back as the start of the next frame rather than delivered.
    const lines = buffer.split("\n");
    const rest = lines.pop() ?? "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed !== "") {
        onChunk?.(readBody(trimmed));
      }
    }
    return rest;
  });

/**
 * Read a `text/event-stream`, delivering one parsed `data:` payload per frame.
 * Comment and keep-alive frames carry no `data:` line and are skipped.
 */
/** The payload of one SSE frame: its `data:` lines, joined, each stripped of the optional leading space. */
const frameData = (frame: string): string =>
  frame
    .split("\n")
    .filter((line) => line.startsWith("data:"))
    .map((line) => line.slice(5).replace(/^ /, ""))
    .join("\n");

const readEventStream = (
  response: Response,
  onChunk: ((chunk: unknown) => void) | undefined,
  signal: AbortSignal | undefined,
): Promise<string> =>
  drainStream(response, signal, (buffer) => {
    // As above: the trailing piece is an incomplete frame and waits for more bytes.
    const frames = buffer.split("\n\n");
    const rest = frames.pop() ?? "";
    for (const frame of frames) {
      const data = frameData(frame);
      if (data !== "") {
        onChunk?.(readBody(data));
      }
    }
    return rest;
  });

/**
 * Run one documented route against a live backend and report what came back.
 *
 * Rejects with a `RequestErrorType` when the request never reached a status —
 * an unparseable payload, a CORS refusal, a dead origin — so the panel can tell
 * "the API said no" apart from "the call never happened".
 */
export const sendRequest = async (input: RequestInputType): Promise<RequestResultType> => {
  const started = performance.now();
  const transport = transportOf(input.meta);

  if (transport === "socket") {
    throw {
      message: "A socket route is opened by the socket panel, not sent as a request.",
      duration: 0,
    } as RequestErrorType;
  }

  let body: BodyInit | undefined;
  if (hasBody(input.meta.method) && input.body) {
    if (input.body.kind === "json") {
      if (input.body.text !== "") {
        try {
          JSON.parse(input.body.text);
        } catch {
          throw { message: "The payload is not valid JSON.", duration: 0 } as RequestErrorType;
        }
        body = input.body.text;
      }
    } else {
      const form = new FormData();
      for (const [name, value] of Object.entries(input.body.fields)) {
        form.append(name, value);
      }
      for (const [name, file] of Object.entries(input.body.files)) {
        form.append(name, file, file.name);
      }
      body = form;
    }
  }

  try {
    const response = await fetch(buildUrl(input), {
      method: input.meta.method.toUpperCase(),
      headers: buildHeaders(input),
      body,
      signal: input.signal,
    });

    let raw: string;
    if (transport === "stream") {
      raw = await readStream(response, input.onChunk, input.signal);
    } else if (transport === "sse") {
      raw = await readEventStream(response, input.onChunk, input.signal);
    } else {
      raw = await response.text();
    }

    return {
      status: response.status,
      statusText: response.statusText,
      duration: Math.round(performance.now() - started),
      headers: collectHeaders(response.headers),
      body: readBody(raw),
      raw,
      ok: response.ok,
    };
  } catch (error) {
    throw {
      message: error instanceof Error ? error.message : "The request failed before reaching the API.",
      duration: Math.round(performance.now() - started),
    } as RequestErrorType;
  }
};

const shellQuote = (value: string): string => `'${value.replace(/'/g, `'\\''`)}'`;

/** The same request as a `curl` line, so it can be replayed outside the browser. */
export const toCurl = (input: RequestInputType): string => {
  const parts = [`curl -X ${input.meta.method.toUpperCase()} ${shellQuote(buildUrl(input))}`];
  for (const [name, value] of Object.entries(buildHeaders(input))) {
    parts.push(`  -H ${shellQuote(`${name}: ${value}`)}`);
  }
  if (hasBody(input.meta.method) && input.body) {
    if (input.body.kind === "json") {
      if (input.body.text !== "") {
        parts.push(`  -d ${shellQuote(input.body.text)}`);
      }
    } else {
      for (const [name, value] of Object.entries(input.body.fields)) {
        if (value !== "") {
          parts.push(`  -F ${shellQuote(`${name}=${value}`)}`);
        }
      }
      for (const [name, file] of Object.entries(input.body.files)) {
        parts.push(`  -F ${shellQuote(`${name}=@${file.name}`)}`);
      }
    }
  }
  return parts.join(" \\\n");
};
