import {
  TASK_CHECKBOX_CHECKED_CLASS,
  TASK_CHECKBOX_CLASS,
  TASK_ITEM_CLASS,
  TASK_LIST_CLASS,
  YOUTUBE_CLASS,
} from "@module/design/components/editor/commands";
import type { MetaType } from "../../shared/story";

const EditorCommandsPreview = () => {
  const constants = [
    ["TASK_LIST_CLASS", TASK_LIST_CLASS],
    ["TASK_ITEM_CLASS", TASK_ITEM_CLASS],
    ["TASK_CHECKBOX_CLASS", TASK_CHECKBOX_CLASS],
    ["TASK_CHECKBOX_CHECKED_CLASS", TASK_CHECKBOX_CHECKED_CLASS],
    ["YOUTUBE_CLASS", YOUTUBE_CLASS],
  ] as const;

  return (
    <div className="grid gap-3">
      {constants.map(([name, value]) => (
        <div key={name} className="rounded border border-border p-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{name}</p>
          <code className="mt-2 block rounded bg-muted px-3 py-2 text-sm">{value}</code>
        </div>
      ))}
    </div>
  );
};

EditorCommandsPreview.displayName = "EditorCommands";

export const meta = {
  title: "Editor.CommandClasses",
  group: "Components",
  tags: [],
  component: EditorCommandsPreview,
  usage: [
    "**Editor command classes** are the Tailwind utility-class constants that the editor command layer writes into generated task lists and embedded YouTube blocks. They keep DOM mutations and the Tailwind-only presentation rules in sync without scattering raw class strings through the codebase.",
    "",
    "**How to use it** — reference these constants only from low-level editor integrations that need to create or inspect the exact structures generated by `commands.ts`. This story exposes the authoritative values so the task-list and embedded-media contract is visible in Storybook instead of being hidden inside the editor implementation.",
    "",
    "**When to use it** — when maintaining the editor's task-list or media command behavior, or when documenting the HTML/CSS contract those commands rely on.",
    "",
    "**When not to use it** — do not treat these constants as user-facing components or copy them into unrelated UI; they are implementation details surfaced here for coverage and reference.",
  ].join("\n"),
} satisfies MetaType<typeof EditorCommandsPreview>;
