#![allow(non_snake_case)]

mod BaggageClaimIcon;
pub use BaggageClaimIcon::*;
mod BaggageScaleIcon;
pub use BaggageScaleIcon::*;
mod BallCrystalIcon;
pub use BallCrystalIcon::*;
mod BaloonIcon;
pub use BaloonIcon::*;
mod BellIcon;
pub use BellIcon::*;
mod BowIcon;
pub use BowIcon::*;
mod CalendarEventIcon;
pub use CalendarEventIcon::*;
mod CamcorderIcon;
pub use CamcorderIcon::*;
mod CandyCaneIcon;
pub use CandyCaneIcon::*;
mod CauldronIcon;
pub use CauldronIcon::*;
mod CelebrationIcon;
pub use CelebrationIcon::*;
mod ChimneyIcon;
pub use ChimneyIcon::*;
mod ChristmasLightIcon;
pub use ChristmasLightIcon::*;
mod ChristmasOrnamentIcon;
pub use ChristmasOrnamentIcon::*;
mod ChristmasStockingIcon;
pub use ChristmasStockingIcon::*;
mod CoffinIcon;
pub use CoffinIcon::*;
mod CornucopiaIcon;
pub use CornucopiaIcon::*;
mod CrackedEggIcon;
pub use CrackedEggIcon::*;
mod EasterEggIcon;
pub use EasterEggIcon::*;
mod EnvelopeHeartIcon;
pub use EnvelopeHeartIcon::*;
mod FrankensteinFaceIcon;
pub use FrankensteinFaceIcon::*;
mod GhostIcon;
pub use GhostIcon::*;
mod Gift2Icon;
pub use Gift2Icon::*;
mod GiftHandIcon;
pub use GiftHandIcon::*;
mod GiftIcon;
pub use GiftIcon::*;
mod GingerbreadManIcon;
pub use GingerbreadManIcon::*;
mod GolfIcon;
pub use GolfIcon::*;
mod HalloweenPumpkinIcon;
pub use HalloweenPumpkinIcon::*;
mod HandGraveIcon;
pub use HandGraveIcon::*;
mod HangingOrnamentsIcon;
pub use HangingOrnamentsIcon::*;
mod IceSkateIcon;
pub use IceSkateIcon::*;
mod MistletoeIcon;
pub use MistletoeIcon::*;
mod MusicIcon;
pub use MusicIcon::*;
mod MusicNoteIcon;
pub use MusicNoteIcon::*;
mod RowingIcon;
pub use RowingIcon::*;
mod SantaHatIcon;
pub use SantaHatIcon::*;
mod ScarecrowIcon;
pub use ScarecrowIcon::*;
mod ScytheIcon;
pub use ScytheIcon::*;
mod Sickle2Icon;
pub use Sickle2Icon::*;
mod SideProfileHeartIcon;
pub use SideProfileHeartIcon::*;
mod SkiingIcon;
pub use SkiingIcon::*;
mod SnowGlobeIcon;
pub use SnowGlobeIcon::*;
mod SnowflakeIcon;
pub use SnowflakeIcon::*;
mod SnowmanHeadIcon;
pub use SnowmanHeadIcon::*;
mod SnowmanIcon;
pub use SnowmanIcon::*;
mod Star2Icon;
pub use Star2Icon::*;
mod StarIcon;
pub use StarIcon::*;
mod TombstoneIcon;
pub use TombstoneIcon::*;
mod VampireIcon;
pub use VampireIcon::*;
mod WalkingTravelerIcon;
pub use WalkingTravelerIcon::*;
mod WaterAerobicsIcon;
pub use WaterAerobicsIcon::*;
mod WinterGloveIcon;
pub use WinterGloveIcon::*;
mod WitchHatIcon;
pub use WitchHatIcon::*;
mod ZombieIcon;
pub use ZombieIcon::*;
