/**
 * Static catalogue of every icon shipped by `@module/design/icons`, generated by scanning
 * `modules/design/src/icons/{fill,outline}/<category>/<sm|md|lg>/<Name>Icon.tsx`. Every icon ships
 * in both the `fill` and `outline` styles; a handful only ship a subset of sizes (see
 * `SIZE_OVERRIDES`). Labels are derived at import time from the icon name and category rather than
 * stored; search tags are curated per icon (see `ICON_TAGS`) so they surface related concepts
 * instead of repeating the icon's own name. The raw `[name, category]` pairs and curated tags live
 * in `./data/` split across several files, each kept under the 500-line budget.
 */
import { ICON_PAIRS } from "./data/icons.pairs";
import { ICON_TAGS } from "./data/icons.tags";

export type IconSizeType = "sm" | "md" | "lg";
export type IconStyleType = "fill" | "outline";

export type IconEntryType = {
  /** Component name, e.g. `"ChevronRightIcon"`. */
  name: string;
  /** Source category folder, e.g. `"arrows"`. */
  category: string;
  /** Human-readable category label, e.g. `"Arrows"`. */
  categoryLabel: string;
  /** Human-readable icon label, e.g. `"Chevron Right"`. */
  label: string;
  /** Curated lowercase search tags (5 per icon), distinct from the icon's own name words. */
  tags: readonly string[];
  /** Sizes this icon ships in (almost always all three). */
  sizes: readonly IconSizeType[];
};

/** Category folder names that need custom casing beyond simple title-casing. */
const CATEGORY_LABEL_OVERRIDES: Readonly<Record<string, string>> = {
  "ar-vr": "AR & VR",
  "ui-layout": "UI & Layout",
  "touch gestures": "Touch Gestures",
  "real estate": "Real Estate",
};

export const categoryLabel = (category: string): string => {
  const preset = CATEGORY_LABEL_OVERRIDES[category];
  if (preset) {
    return preset;
  }
  return category
    .split(/[-\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

/** Split a PascalCase icon name (trailing "Icon" stripped) into its constituent words. */
export const nameWords = (name: string): string[] => {
  const trimmed = name.endsWith("Icon") ? name.slice(0, -4) : name;
  const spaced = trimmed
    .replace(/(?<!^)(?<![A-Z0-9])(?=[A-Z])/g, " ")
    .replace(/(?<=[A-Za-z])(?=[0-9])/g, " ")
    .replace(/(?<=[0-9])(?=[A-Za-z])/g, " ");
  return spaced.split(" ").filter(Boolean);
};

export const iconLabel = (name: string): string => nameWords(name).join(" ");

const ALL_SIZES: readonly IconSizeType[] = ["sm", "md", "lg"];

/** Icons that don't ship all three sizes, keyed by `"<category>/<name>"`. */
const SIZE_OVERRIDES: Readonly<Record<string, readonly IconSizeType[]>> = {
  "animals-nature/Rat5Icon": ["lg"],
  "animals-nature/Rat4Icon": ["lg"],
  "animals-nature/Sheep2Icon": ["lg"],
  "animals-nature/Rat3Icon": ["lg"],
  "business-finance/UserCoin2Icon": ["lg"],
  "business-finance/CryptoExchangeIcon": ["lg"],
  "sport/Bicycle3Icon": ["md", "lg"],
  "sport/OlympicGamesIcon": ["lg"],
  "transportation/Bicycle3Icon": ["sm"],
  "ui-layout/HammerScrewdriverIcon": ["md", "lg"],
  "ui-layout/WrenchesIcon": ["md", "lg"],
  "users/People2Icon": ["lg"],
};

export const ICONS: readonly IconEntryType[] = ICON_PAIRS.map(([name, category]) => {
  return {
    name,
    category,
    categoryLabel: categoryLabel(category),
    label: iconLabel(name),
    tags: ICON_TAGS[`${category}/${name}`] ?? [],
    sizes: SIZE_OVERRIDES[`${category}/${name}`] ?? ALL_SIZES,
  };
});

export const ICON_CATEGORIES: readonly string[] = Array.from(new Set(ICONS.map((icon) => icon.category))).sort((a, b) =>
  categoryLabel(a).localeCompare(categoryLabel(b)),
);
