#![allow(non_snake_case)]

mod BambooIcon;
pub use BambooIcon::*;
mod BatIcon;
pub use BatIcon::*;
mod Bear2Icon;
pub use Bear2Icon::*;
mod BearIcon;
pub use BearIcon::*;
mod BeeIcon;
pub use BeeIcon::*;
mod BonesIcon;
pub use BonesIcon::*;
mod BugIcon;
pub use BugIcon::*;
mod ButterflyIcon;
pub use ButterflyIcon::*;
mod CactusIcon;
pub use CactusIcon::*;
mod Camping2Icon;
pub use Camping2Icon::*;
mod CampingIcon;
pub use CampingIcon::*;
mod CatIcon;
pub use CatIcon::*;
mod Chicken2Icon;
pub use Chicken2Icon::*;
mod ChickenIcon;
pub use ChickenIcon::*;
mod Clover2Icon;
pub use Clover2Icon::*;
mod CloverIcon;
pub use CloverIcon::*;
mod CollarIcon;
pub use CollarIcon::*;
mod CowIcon;
pub use CowIcon::*;
mod CrabIcon;
pub use CrabIcon::*;
mod DeerIcon;
pub use DeerIcon::*;
mod DogHouseIcon;
pub use DogHouseIcon::*;
mod DogIcon;
pub use DogIcon::*;
mod DogLeashIcon;
pub use DogLeashIcon::*;
mod Droplet2Icon;
pub use Droplet2Icon::*;
mod DropletIcon;
pub use DropletIcon::*;
mod DuckIcon;
pub use DuckIcon::*;
mod EarthLeafIcon;
pub use EarthLeafIcon::*;
mod EarthSectionIcon;
pub use EarthSectionIcon::*;
mod ElephantIcon;
pub use ElephantIcon::*;
mod Feather2Icon;
pub use Feather2Icon::*;
mod FeatherIcon;
pub use FeatherIcon::*;
mod FireFlameIcon;
pub use FireFlameIcon::*;
mod FireIcon;
pub use FireIcon::*;
mod FishBoneIcon;
pub use FishBoneIcon::*;
mod FishIcon;
pub use FishIcon::*;
mod Flower2Icon;
pub use Flower2Icon::*;
mod Flower3Icon;
pub use Flower3Icon::*;
mod Flower4Icon;
pub use Flower4Icon::*;
mod Flower5Icon;
pub use Flower5Icon::*;
mod Flower6Icon;
pub use Flower6Icon::*;
mod FlowerBouquetIcon;
pub use FlowerBouquetIcon::*;
mod FlowerIcon;
pub use FlowerIcon::*;
mod FlowerLotusIcon;
pub use FlowerLotusIcon::*;
mod FoodCatIcon;
pub use FoodCatIcon::*;
mod FoodDogIcon;
pub use FoodDogIcon::*;
mod FoodPetIcon;
pub use FoodPetIcon::*;
mod GooseIcon;
pub use GooseIcon::*;
mod GrainIcon;
pub use GrainIcon::*;
mod Horse2Icon;
pub use Horse2Icon::*;
mod HorseIcon;
pub use HorseIcon::*;
mod HorseshoeIcon;
pub use HorseshoeIcon::*;
mod JellyfishIcon;
pub use JellyfishIcon::*;
mod LadybugIcon;
pub use LadybugIcon::*;
mod LeafIcon;
pub use LeafIcon::*;
mod LeafMapleIcon;
pub use LeafMapleIcon::*;
mod Leaves2Icon;
pub use Leaves2Icon::*;
mod Leaves3Icon;
pub use Leaves3Icon::*;
mod LeavesIcon;
pub use LeavesIcon::*;
mod LobsterIcon;
pub use LobsterIcon::*;
mod MountainIcon;
pub use MountainIcon::*;
mod MowerIcon;
pub use MowerIcon::*;
mod MushroomIcon;
pub use MushroomIcon::*;
mod OctopusIcon;
pub use OctopusIcon::*;
mod OwlIcon;
pub use OwlIcon::*;
mod PandaIcon;
pub use PandaIcon::*;
mod Park2Icon;
pub use Park2Icon::*;
mod ParkIcon;
pub use ParkIcon::*;
mod ParrotIcon;
pub use ParrotIcon::*;
mod PawIcon;
pub use PawIcon::*;
mod PenguinIcon;
pub use PenguinIcon::*;
mod PickaxeIcon;
pub use PickaxeIcon::*;
mod PigIcon;
pub use PigIcon::*;
mod RabbitIcon;
pub use RabbitIcon::*;
mod Rat2Icon;
pub use Rat2Icon::*;
mod Rat3Icon;
pub use Rat3Icon::*;
mod Rat4Icon;
pub use Rat4Icon::*;
mod Rat5Icon;
pub use Rat5Icon::*;
mod RatIcon;
pub use RatIcon::*;
mod Seedling2Icon;
pub use Seedling2Icon::*;
mod Seedling3Icon;
pub use Seedling3Icon::*;
mod SeedlingIcon;
pub use SeedlingIcon::*;
mod SharkIcon;
pub use SharkIcon::*;
mod SharkWaterIcon;
pub use SharkWaterIcon::*;
mod Sheep2Icon;
pub use Sheep2Icon::*;
mod SheepIcon;
pub use SheepIcon::*;
mod ShellIcon;
pub use ShellIcon::*;
mod Shovel2Icon;
pub use Shovel2Icon::*;
mod ShovelIcon;
pub use ShovelIcon::*;
mod ShrimpIcon;
pub use ShrimpIcon::*;
mod SlothIcon;
pub use SlothIcon::*;
mod SnakeIcon;
pub use SnakeIcon::*;
mod SpiderIcon;
pub use SpiderIcon::*;
mod SpiderWebIcon;
pub use SpiderWebIcon::*;
mod TeddyBearIcon;
pub use TeddyBearIcon::*;
mod Tree2Icon;
pub use Tree2Icon::*;
mod Tree3Icon;
pub use Tree3Icon::*;
mod TreeIcon;
pub use TreeIcon::*;
mod TreePalmIcon;
pub use TreePalmIcon::*;
mod Trees2Icon;
pub use Trees2Icon::*;
mod Trees3Icon;
pub use Trees3Icon::*;
mod Trees4Icon;
pub use Trees4Icon::*;
mod TreesIcon;
pub use TreesIcon::*;
mod TurkeyIcon;
pub use TurkeyIcon::*;
mod TurtleIcon;
pub use TurtleIcon::*;
mod WaterSurfaceIcon;
pub use WaterSurfaceIcon::*;
mod WaterWaveIcon;
pub use WaterWaveIcon::*;
mod WateringPlantsIcon;
pub use WateringPlantsIcon::*;
mod WeedIcon;
pub use WeedIcon::*;
mod Windmill2Icon;
pub use Windmill2Icon::*;
mod Windmill3Icon;
pub use Windmill3Icon::*;
mod WolfIcon;
pub use WolfIcon::*;
mod WoodIcon;
pub use WoodIcon::*;
mod WoolBallIcon;
pub use WoolBallIcon::*;
