#![allow(non_snake_case)]

mod Archive2Icon;
pub use Archive2Icon::*;
mod ArchiveCheckIcon;
pub use ArchiveCheckIcon::*;
mod ArchiveContent2Icon;
pub use ArchiveContent2Icon::*;
mod ArchiveContentIcon;
pub use ArchiveContentIcon::*;
mod ArchiveDocCheckIcon;
pub use ArchiveDocCheckIcon::*;
mod ArchiveFileCheckIcon;
pub use ArchiveFileCheckIcon::*;
mod ArchiveFileIcon;
pub use ArchiveFileIcon::*;
mod ArchiveIcon;
pub use ArchiveIcon::*;
mod BoxArchiveIcon;
pub use BoxArchiveIcon::*;
mod Copy2Icon;
pub use Copy2Icon::*;
mod File2Icon;
pub use File2Icon::*;
mod FileAacIcon;
pub use FileAacIcon::*;
mod FileAlertIcon;
pub use FileAlertIcon::*;
mod FileAviIcon;
pub use FileAviIcon::*;
mod FileBmpIcon;
pub use FileBmpIcon::*;
mod FileBookmarkIcon;
pub use FileBookmarkIcon::*;
mod FileChartBarIcon;
pub use FileChartBarIcon::*;
mod FileChartPieIcon;
pub use FileChartPieIcon::*;
mod FileCheckIcon;
pub use FileCheckIcon::*;
mod FileClockIcon;
pub use FileClockIcon::*;
mod FileCloudIcon;
pub use FileCloudIcon::*;
mod FileContentIcon;
pub use FileContentIcon::*;
mod FileCopiesIcon;
pub use FileCopiesIcon::*;
mod FileCsvIcon;
pub use FileCsvIcon::*;
mod FileDmgIcon;
pub use FileDmgIcon::*;
mod FileDocIcon;
pub use FileDocIcon::*;
mod FileDocxIcon;
pub use FileDocxIcon::*;
mod FileDownloadIcon;
pub use FileDownloadIcon::*;
mod FileEpubIcon;
pub use FileEpubIcon::*;
mod FileExeIcon;
pub use FileExeIcon::*;
mod FileFlashIcon;
pub use FileFlashIcon::*;
mod FileFlvIcon;
pub use FileFlvIcon::*;
mod FileGalleryIcon;
pub use FileGalleryIcon::*;
mod FileGpxIcon;
pub use FileGpxIcon::*;
mod FileHeartIcon;
pub use FileHeartIcon::*;
mod FileIcon;
pub use FileIcon::*;
mod FileIcsIcon;
pub use FileIcsIcon::*;
mod FileImageIcon;
pub use FileImageIcon::*;
mod FileInfoIcon;
pub use FileInfoIcon::*;
mod FileIsoIcon;
pub use FileIsoIcon::*;
mod FileJarIcon;
pub use FileJarIcon::*;
mod FileLinkIcon;
pub use FileLinkIcon::*;
mod FileLockIcon;
pub use FileLockIcon::*;
mod FileMinusIcon;
pub use FileMinusIcon::*;
mod FileMkvIcon;
pub use FileMkvIcon::*;
mod FileMoneyIcon;
pub use FileMoneyIcon::*;
mod FileMovIcon;
pub use FileMovIcon::*;
mod FileMp3Icon;
pub use FileMp3Icon::*;
mod FileMp4Icon;
pub use FileMp4Icon::*;
mod FileMpgIcon;
pub use FileMpgIcon::*;
mod FileMusicIcon;
pub use FileMusicIcon::*;
mod FileNewIcon;
pub use FileNewIcon::*;
mod FileNoAccessIcon;
pub use FileNoAccessIcon::*;
mod FilePenIcon;
pub use FilePenIcon::*;
mod FilePlayIcon;
pub use FilePlayIcon::*;
mod FilePptxIcon;
pub use FilePptxIcon::*;
mod FileQuestionIcon;
pub use FileQuestionIcon::*;
mod FileRarIcon;
pub use FileRarIcon::*;
mod FileReplaceIcon;
pub use FileReplaceIcon::*;
mod FileRssIcon;
pub use FileRssIcon::*;
mod FileRtfIcon;
pub use FileRtfIcon::*;
mod FileSearchIcon;
pub use FileSearchIcon::*;
mod FileSettingsIcon;
pub use FileSettingsIcon::*;
mod FileSliderIcon;
pub use FileSliderIcon::*;
mod FileSrtIcon;
pub use FileSrtIcon::*;
mod FileStarIcon;
pub use FileStarIcon::*;
mod FileSyncIcon;
pub use FileSyncIcon::*;
mod FileTxtIcon;
pub use FileTxtIcon::*;
mod FileUploadIcon;
pub use FileUploadIcon::*;
mod FileUserIcon;
pub use FileUserIcon::*;
mod FileUsersIcon;
pub use FileUsersIcon::*;
mod FileVectorIcon;
pub use FileVectorIcon::*;
mod FileVolumeIcon;
pub use FileVolumeIcon::*;
mod FileVvtIcon;
pub use FileVvtIcon::*;
mod FileWavIcon;
pub use FileWavIcon::*;
mod FileXlsxIcon;
pub use FileXlsxIcon::*;
mod FileXmarkIcon;
pub use FileXmarkIcon::*;
mod FileZipIcon;
pub use FileZipIcon::*;
mod FilesContentIcon;
pub use FilesContentIcon::*;
mod FilesIcon;
pub use FilesIcon::*;
mod FloppyDiskIcon;
pub use FloppyDiskIcon::*;
mod Folder2Icon;
pub use Folder2Icon::*;
mod FolderAlertIcon;
pub use FolderAlertIcon::*;
mod FolderBanIcon;
pub use FolderBanIcon::*;
mod FolderBookmarkIcon;
pub use FolderBookmarkIcon::*;
mod FolderChartBarIcon;
pub use FolderChartBarIcon::*;
mod FolderChartPieIcon;
pub use FolderChartPieIcon::*;
mod FolderCheckIcon;
pub use FolderCheckIcon::*;
mod FolderClockIcon;
pub use FolderClockIcon::*;
mod FolderCloudIcon;
pub use FolderCloudIcon::*;
mod FolderContentIcon;
pub use FolderContentIcon::*;
mod FolderDownloadIcon;
pub use FolderDownloadIcon::*;
mod FolderGalleryIcon;
pub use FolderGalleryIcon::*;
mod FolderHeartIcon;
pub use FolderHeartIcon::*;
mod FolderIcon;
pub use FolderIcon::*;
mod FolderImageIcon;
pub use FolderImageIcon::*;
mod FolderInfoIcon;
pub use FolderInfoIcon::*;
mod FolderLinkIcon;
pub use FolderLinkIcon::*;
mod FolderLockIcon;
pub use FolderLockIcon::*;
mod FolderMinusIcon;
pub use FolderMinusIcon::*;
mod FolderMoneyIcon;
pub use FolderMoneyIcon::*;
mod FolderMusicIcon;
pub use FolderMusicIcon::*;
mod FolderOpen2Icon;
pub use FolderOpen2Icon::*;
mod FolderOpenIcon;
pub use FolderOpenIcon::*;
mod FolderPenIcon;
pub use FolderPenIcon::*;
mod FolderPlayIcon;
pub use FolderPlayIcon::*;
mod FolderPlusIcon;
pub use FolderPlusIcon::*;
mod FolderQuestionIcon;
pub use FolderQuestionIcon::*;
mod FolderRefreshIcon;
pub use FolderRefreshIcon::*;
mod FolderReplaceIcon;
pub use FolderReplaceIcon::*;
mod FolderSearchIcon;
pub use FolderSearchIcon::*;
mod FolderSettingsIcon;
pub use FolderSettingsIcon::*;
mod FolderSliderIcon;
pub use FolderSliderIcon::*;
mod FolderStarIcon;
pub use FolderStarIcon::*;
mod FolderUploadIcon;
pub use FolderUploadIcon::*;
mod FolderUserIcon;
pub use FolderUserIcon::*;
mod FolderUsersIcon;
pub use FolderUsersIcon::*;
mod FolderVectorIcon;
pub use FolderVectorIcon::*;
mod FolderVolumeIcon;
pub use FolderVolumeIcon::*;
mod InboxStackIcon;
pub use InboxStackIcon::*;
mod NoteIcon;
pub use NoteIcon::*;
mod ObjAddIcon;
pub use ObjAddIcon::*;
mod ObjRemoveIcon;
pub use ObjRemoveIcon::*;
mod Page2Icon;
pub use Page2Icon::*;
mod Page3Icon;
pub use Page3Icon::*;
mod Page4Icon;
pub use Page4Icon::*;
mod PageIcon;
pub use PageIcon::*;
mod PrintIcon;
pub use PrintIcon::*;
mod RawImageIcon;
pub use RawImageIcon::*;
mod ZippedFile2Icon;
pub use ZippedFile2Icon::*;
mod ZippedFileIcon;
pub use ZippedFileIcon::*;
