#![allow(non_snake_case)]

mod BullhornIcon;
pub use BullhornIcon::*;
mod ChartActivity2Icon;
pub use ChartActivity2Icon::*;
mod ClarinetIcon;
pub use ClarinetIcon::*;
mod CompactDiskIcon;
pub use CompactDiskIcon::*;
mod DigitalPianoIcon;
pub use DigitalPianoIcon::*;
mod DrumsIcon;
pub use DrumsIcon::*;
mod GuitarIcon;
pub use GuitarIcon::*;
mod MediaPlaylistIcon;
pub use MediaPlaylistIcon::*;
mod MegaphoneIcon;
pub use MegaphoneIcon::*;
mod MicrophoneSlashIcon;
pub use MicrophoneSlashIcon::*;
mod MobileMusicIcon;
pub use MobileMusicIcon::*;
mod MusicAlbumIcon;
pub use MusicAlbumIcon::*;
mod MusicCloudIcon;
pub use MusicCloudIcon::*;
mod MusicPlaylistIcon;
pub use MusicPlaylistIcon::*;
mod Piano2Icon;
pub use Piano2Icon::*;
mod PianoIcon;
pub use PianoIcon::*;
mod PodcastIcon;
pub use PodcastIcon::*;
mod RadioIcon;
pub use RadioIcon::*;
mod RecordPlayerIcon;
pub use RecordPlayerIcon::*;
mod TrumpetIcon;
pub use TrumpetIcon::*;
mod ViolinIcon;
pub use ViolinIcon::*;
mod VoiceChatIcon;
pub use VoiceChatIcon::*;
mod Volume2Icon;
pub use Volume2Icon::*;
mod VolumeIcon;
pub use VolumeIcon::*;
mod VolumeMinusIcon;
pub use VolumeMinusIcon::*;
mod VolumeOffIcon;
pub use VolumeOffIcon::*;
mod VolumePlusIcon;
pub use VolumePlusIcon::*;
mod VolumeUpIcon;
pub use VolumeUpIcon::*;
mod VolumeXmarkIcon;
pub use VolumeXmarkIcon::*;
mod WaveformLinesIcon;
pub use WaveformLinesIcon::*;
