#![allow(non_snake_case)]

pub mod accessibility;
#[path = "animals-nature/mod.rs"]
pub mod animals_nature;
#[path = "ar-vr/mod.rs"]
pub mod ar_vr;
pub mod arrows;
#[path = "bookmarks-favorites/mod.rs"]
pub mod bookmarks_favorites;
#[path = "business-finance/mod.rs"]
pub mod business_finance;
pub mod charts;
pub mod communication;
#[path = "design-development/mod.rs"]
pub mod design_development;
pub mod editing;
pub mod emoji;
#[path = "energy-environment/mod.rs"]
pub mod energy_environment;
pub mod entertainment;
#[path = "family-kids/mod.rs"]
pub mod family_kids;
#[path = "farming-gardening/mod.rs"]
pub mod farming_gardening;
#[path = "fashion-beauty/mod.rs"]
pub mod fashion_beauty;
#[path = "files-folders/mod.rs"]
pub mod files_folders;
#[path = "filtering-sorting/mod.rs"]
pub mod filtering_sorting;
pub mod food;
pub mod gaming;
#[path = "healthcare-medical/mod.rs"]
pub mod healthcare_medical;
pub mod holidays;
#[path = "home-buildings/mod.rs"]
pub mod home_buildings;
pub mod loaders;
#[path = "love-romance/mod.rs"]
pub mod love_romance;
#[path = "maps-location/mod.rs"]
pub mod maps_location;
#[path = "military-war/mod.rs"]
pub mod military_war;
#[path = "photography-video/mod.rs"]
pub mod photography_video;
#[path = "real estate/mod.rs"]
pub mod real_estate;
#[path = "school-education/mod.rs"]
pub mod school_education;
pub mod security;
pub mod shopping;
#[path = "signs-symbols/mod.rs"]
pub mod signs_symbols;
#[path = "sound-music/mod.rs"]
pub mod sound_music;
pub mod sport;
#[path = "technology-devices/mod.rs"]
pub mod technology_devices;
pub mod time;
#[path = "touch gestures/mod.rs"]
pub mod touch_gestures;
pub mod transportation;
pub mod travel;
#[path = "ui-layout/mod.rs"]
pub mod ui_layout;
pub mod users;
pub mod weather;
