#![allow(non_snake_case)]

mod AirBombIcon;
pub use AirBombIcon::*;
mod AssaultRifleIcon;
pub use AssaultRifleIcon::*;
mod BulletsIcon;
pub use BulletsIcon::*;
mod DynamiteIcon;
pub use DynamiteIcon::*;
mod GasMaskIcon;
pub use GasMaskIcon::*;
mod GrenadeIcon;
pub use GrenadeIcon::*;
mod HandgunIcon;
pub use HandgunIcon::*;
mod MilitaryCampIcon;
pub use MilitaryCampIcon::*;
mod MilitaryHelmetIcon;
pub use MilitaryHelmetIcon::*;
mod MilitaryKnifeIcon;
pub use MilitaryKnifeIcon::*;
mod MilitaryMedalIcon;
pub use MilitaryMedalIcon::*;
mod MilitaryRankIcon;
pub use MilitaryRankIcon::*;
mod MilitaryTagsIcon;
pub use MilitaryTagsIcon::*;
mod MilitaryTankIcon;
pub use MilitaryTankIcon::*;
mod MilitaryVestIcon;
pub use MilitaryVestIcon::*;
mod MissilesIcon;
pub use MissilesIcon::*;
mod ParachuteIcon;
pub use ParachuteIcon::*;
mod ShotgunIcon;
pub use ShotgunIcon::*;
mod SniperRifleIcon;
pub use SniperRifleIcon::*;
mod SubmachineGunIcon;
pub use SubmachineGunIcon::*;
