[package]
name = "design-rust"
version = "0.1.0"
edition = "2024"
exclude = ["src/icons"]

[dependencies]
dioxus = { version = "0.7.9", default-features = false, features = ["macro", "html", "signals", "hooks", "mounted", "document"] }
tw_merge = "0.1.21"
design-icons = { path = "src/icons" }

[dev-dependencies]
dioxus-ssr = "0.7.9"
