#![allow(non_snake_case)]

mod AtSignIcon;
pub use AtSignIcon::*;
mod ChatBubbleForwardIcon;
pub use ChatBubbleForwardIcon::*;
mod ChatBubblePlusIcon;
pub use ChatBubblePlusIcon::*;
mod CircleComposeIcon;
pub use CircleComposeIcon::*;
mod Compose2Icon;
pub use Compose2Icon::*;
mod Compose3Icon;
pub use Compose3Icon::*;
mod Compose4Icon;
pub use Compose4Icon::*;
mod ComposeIcon;
pub use ComposeIcon::*;
mod ConnectedDots3Icon;
pub use ConnectedDots3Icon::*;
mod ConnectedDotsIcon;
pub use ConnectedDotsIcon::*;
mod EnvelopeContentIcon;
pub use EnvelopeContentIcon::*;
mod EnvelopeIcon;
pub use EnvelopeIcon::*;
mod EnvelopeOpenIcon;
pub use EnvelopeOpenIcon::*;
mod LanguageIcon;
pub use LanguageIcon::*;
mod Message2ContentIcon;
pub use Message2ContentIcon::*;
mod Message2Icon;
pub use Message2Icon::*;
mod MessageBubbleUserIcon;
pub use MessageBubbleUserIcon::*;
mod MessageIcon;
pub use MessageIcon::*;
mod MessagesIcon;
pub use MessagesIcon::*;
mod MsgAlertIcon;
pub use MsgAlertIcon::*;
mod MsgContentIcon;
pub use MsgContentIcon::*;
mod MsgIcon;
pub use MsgIcon::*;
mod MsgSettingsIcon;
pub use MsgSettingsIcon::*;
mod MsgsIcon;
pub use MsgsIcon::*;
mod PaperPlane2Icon;
pub use PaperPlane2Icon::*;
mod PaperPlaneIcon;
pub use PaperPlaneIcon::*;
mod Paperclip2Icon;
pub use Paperclip2Icon::*;
mod PaperclipIcon;
pub use PaperclipIcon::*;
mod Pen2Icon;
pub use Pen2Icon::*;
mod Pen2WritingIcon;
pub use Pen2WritingIcon::*;
mod Pen3WritingIcon;
pub use Pen3WritingIcon::*;
mod PenIcon;
pub use PenIcon::*;
mod PenWritingIcon;
pub use PenWritingIcon::*;
