#![allow(non_snake_case)]

mod AlarmClockIcon;
pub use AlarmClockIcon::*;
mod BellPlusIcon;
pub use BellPlusIcon::*;
mod BellSlashIcon;
pub use BellSlashIcon::*;
mod CalendarCheck2Icon;
pub use CalendarCheck2Icon::*;
mod CalendarCheckIcon;
pub use CalendarCheckIcon::*;
mod CalendarClockIcon;
pub use CalendarClockIcon::*;
mod CalendarDayViewIcon;
pub use CalendarDayViewIcon::*;
mod CalendarIcon;
pub use CalendarIcon::*;
mod CalendarPlusIcon;
pub use CalendarPlusIcon::*;
mod Clock2Icon;
pub use Clock2Icon::*;
mod ClockIcon;
pub use ClockIcon::*;
mod HourglassIcon;
pub use HourglassIcon::*;
mod InfinityIcon;
pub use InfinityIcon::*;
mod StopwatchIcon;
pub use StopwatchIcon::*;
