#![allow(non_snake_case)]

mod AcornIcon;
pub use AcornIcon::*;
mod AddRecipeIcon;
pub use AddRecipeIcon::*;
mod AlcoholWarningIcon;
pub use AlcoholWarningIcon::*;
mod AppleIcon;
pub use AppleIcon::*;
mod AubergineIcon;
pub use AubergineIcon::*;
mod AvocadoIcon;
pub use AvocadoIcon::*;
mod BabyBottle2Icon;
pub use BabyBottle2Icon::*;
mod BabyBottleIcon;
pub use BabyBottleIcon::*;
mod BaconIcon;
pub use BaconIcon::*;
mod BagFastIcon;
pub use BagFastIcon::*;
mod BaguetteIcon;
pub use BaguetteIcon::*;
mod BananaIcon;
pub use BananaIcon::*;
mod BarbecueGrill2Icon;
pub use BarbecueGrill2Icon::*;
mod BarbecueGrillIcon;
pub use BarbecueGrillIcon::*;
mod BeerMug2Icon;
pub use BeerMug2Icon::*;
mod BeerMugIcon;
pub use BeerMugIcon::*;
mod BeverageCupIcon;
pub use BeverageCupIcon::*;
mod BlenderIcon;
pub use BlenderIcon::*;
mod BlueberriesIcon;
pub use BlueberriesIcon::*;
mod BoilingPotIcon;
pub use BoilingPotIcon::*;
mod BottleIcon;
pub use BottleIcon::*;
mod BowlIcon;
pub use BowlIcon::*;
mod BowlRiceIcon;
pub use BowlRiceIcon::*;
mod BreadLoafIcon;
pub use BreadLoafIcon::*;
mod BreadSliceIcon;
pub use BreadSliceIcon::*;
mod BriocheIcon;
pub use BriocheIcon::*;
mod BroccoliIcon;
pub use BroccoliIcon::*;
mod ButterIcon;
pub use ButterIcon::*;
mod Cake2Icon;
pub use Cake2Icon::*;
mod Cake3Icon;
pub use Cake3Icon::*;
mod CakeSliceIcon;
pub use CakeSliceIcon::*;
mod CandleIcon;
pub use CandleIcon::*;
mod CandyIcon;
pub use CandyIcon::*;
mod CannedFoodIcon;
pub use CannedFoodIcon::*;
mod CarrotIcon;
pub use CarrotIcon::*;
mod ChampagneGlassIcon;
pub use ChampagneGlassIcon::*;
mod CheersGlassesIcon;
pub use CheersGlassesIcon::*;
mod Cheese2Icon;
pub use Cheese2Icon::*;
mod CheeseIcon;
pub use CheeseIcon::*;
mod CheeseburgerIcon;
pub use CheeseburgerIcon::*;
mod ChefHatIcon;
pub use ChefHatIcon::*;
mod ChefIcon;
pub use ChefIcon::*;
mod CherriesIcon;
pub use CherriesIcon::*;
mod ChickenLegIcon;
pub use ChickenLegIcon::*;
mod ChocoCreamIcon;
pub use ChocoCreamIcon::*;
mod ChocolateBarIcon;
pub use ChocolateBarIcon::*;
mod ChocolateMousseIcon;
pub use ChocolateMousseIcon::*;
mod ChurrosIcon;
pub use ChurrosIcon::*;
mod ClocheIcon;
pub use ClocheIcon::*;
mod CocktailIcon;
pub use CocktailIcon::*;
mod CocktailShakerIcon;
pub use CocktailShakerIcon::*;
mod CoffeeBeansIcon;
pub use CoffeeBeansIcon::*;
mod CoffeeCupIcon;
pub use CoffeeCupIcon::*;
mod Cookbook2Icon;
pub use Cookbook2Icon::*;
mod CookbookIcon;
pub use CookbookIcon::*;
mod CookiesIcon;
pub use CookiesIcon::*;
mod CookingPotIcon;
pub use CookingPotIcon::*;
mod CornIcon;
pub use CornIcon::*;
mod CrepeIcon;
pub use CrepeIcon::*;
mod CroissantIcon;
pub use CroissantIcon::*;
mod CrumpetIcon;
pub use CrumpetIcon::*;
mod CupcakeIcon;
pub use CupcakeIcon::*;
mod Cutlery2Icon;
pub use Cutlery2Icon::*;
mod Cutlery3Icon;
pub use Cutlery3Icon::*;
mod Cutlery4Icon;
pub use Cutlery4Icon::*;
mod CutleryIcon;
pub use CutleryIcon::*;
mod DetoxDrinkIcon;
pub use DetoxDrinkIcon::*;
mod DietAppleIcon;
pub use DietAppleIcon::*;
mod DietCalendarIcon;
pub use DietCalendarIcon::*;
mod DishwasherIcon;
pub use DishwasherIcon::*;
mod DonutIcon;
pub use DonutIcon::*;
mod DrinkIcon;
pub use DrinkIcon::*;
mod DrinkMenuIcon;
pub use DrinkMenuIcon::*;
mod EggsIcon;
pub use EggsIcon::*;
mod EnergyDrinkCanIcon;
pub use EnergyDrinkCanIcon::*;
mod EnergyIcon;
pub use EnergyIcon::*;
mod FarmerMarketIcon;
pub use FarmerMarketIcon::*;
mod FoodBasketIcon;
pub use FoodBasketIcon::*;
mod FoodScale2Icon;
pub use FoodScale2Icon::*;
mod FoodScale3Icon;
pub use FoodScale3Icon::*;
mod FoodScaleIcon;
pub use FoodScaleIcon::*;
mod FoodServiceIcon;
pub use FoodServiceIcon::*;
mod FoodSupplementIcon;
pub use FoodSupplementIcon::*;
mod FrenchFriesIcon;
pub use FrenchFriesIcon::*;
mod FridgeIcon;
pub use FridgeIcon::*;
mod FriedEggIcon;
pub use FriedEggIcon::*;
mod FryingPanIcon;
pub use FryingPanIcon::*;
mod GarlicIcon;
pub use GarlicIcon::*;
mod GelatinDessertIcon;
pub use GelatinDessertIcon::*;
mod GlassWaterIcon;
pub use GlassWaterIcon::*;
mod GrapesIcon;
pub use GrapesIcon::*;
mod GrillToolsIcon;
pub use GrillToolsIcon::*;
mod HandMixerIcon;
pub use HandMixerIcon::*;
mod HandPickingPearIcon;
pub use HandPickingPearIcon::*;
mod HazelnutIcon;
pub use HazelnutIcon::*;
mod HoneyIcon;
pub use HoneyIcon::*;
mod HotDogIcon;
pub use HotDogIcon::*;
mod HotPepperIcon;
pub use HotPepperIcon::*;
mod IceCream2Icon;
pub use IceCream2Icon::*;
mod IceCreamIcon;
pub use IceCreamIcon::*;
mod JamIcon;
pub use JamIcon::*;
mod JuiceIcon;
pub use JuiceIcon::*;
mod KettleIcon;
pub use KettleIcon::*;
mod KitchenHobsIcon;
pub use KitchenHobsIcon::*;
mod KitchenHoodIcon;
pub use KitchenHoodIcon::*;
mod KitchenTimerIcon;
pub use KitchenTimerIcon::*;
mod KiwiIcon;
pub use KiwiIcon::*;
mod KnifeIcon;
pub use KnifeIcon::*;
mod LemonIcon;
pub use LemonIcon::*;
mod LemonWedgeIcon;
pub use LemonWedgeIcon::*;
mod LighterIcon;
pub use LighterIcon::*;
mod LollipopIcon;
pub use LollipopIcon::*;
mod MatchLighterIcon;
pub use MatchLighterIcon::*;
mod MealHeartIcon;
pub use MealHeartIcon::*;
mod MeasuringCupIcon;
pub use MeasuringCupIcon::*;
mod MeatLegIcon;
pub use MeatLegIcon::*;
mod MicrowaveIcon;
pub use MicrowaveIcon::*;
mod MilkContainerIcon;
pub use MilkContainerIcon::*;
mod MokaPotIcon;
pub use MokaPotIcon::*;
mod MuffinIcon;
pub use MuffinIcon::*;
mod MugIcon;
pub use MugIcon::*;
mod NoodlesIcon;
pub use NoodlesIcon::*;
mod NutritionPlan2Icon;
pub use NutritionPlan2Icon::*;
mod NutritionPlanIcon;
pub use NutritionPlanIcon::*;
mod OilBottleIcon;
pub use OilBottleIcon::*;
mod OnionIcon;
pub use OnionIcon::*;
mod OrangeIcon;
pub use OrangeIcon::*;
mod OutdoorSeatingIcon;
pub use OutdoorSeatingIcon::*;
mod OvenIcon;
pub use OvenIcon::*;
mod PancakeStackIcon;
pub use PancakeStackIcon::*;
mod PastaPlateIcon;
pub use PastaPlateIcon::*;
mod PeanutIcon;
pub use PeanutIcon::*;
mod PearIcon;
pub use PearIcon::*;
mod PeasIcon;
pub use PeasIcon::*;
mod PepperIcon;
pub use PepperIcon::*;
mod PickleIcon;
pub use PickleIcon::*;
mod PicnicBasketIcon;
pub use PicnicBasketIcon::*;
mod PieIcon;
pub use PieIcon::*;
mod PineappleIcon;
pub use PineappleIcon::*;
mod PizzaIcon;
pub use PizzaIcon::*;
mod PizzaSliceIcon;
pub use PizzaSliceIcon::*;
mod PlateIcon;
pub use PlateIcon::*;
mod PopcornIcon;
pub use PopcornIcon::*;
mod PopsicleIcon;
pub use PopsicleIcon::*;
mod PotatoChipsIcon;
pub use PotatoChipsIcon::*;
mod PotatoIcon;
pub use PotatoIcon::*;
mod ProteinShakerIcon;
pub use ProteinShakerIcon::*;
mod PumpkinIcon;
pub use PumpkinIcon::*;
mod RecipeIcon;
pub use RecipeIcon::*;
mod ReservedTagIcon;
pub use ReservedTagIcon::*;
mod RestaurantMenuIcon;
pub use RestaurantMenuIcon::*;
mod RoastChickenIcon;
pub use RoastChickenIcon::*;
mod RoastTurkeyIcon;
pub use RoastTurkeyIcon::*;
mod RollingPinIcon;
pub use RollingPinIcon::*;
mod RomanticDinnerIcon;
pub use RomanticDinnerIcon::*;
mod SaladIcon;
pub use SaladIcon::*;
mod SaltShakerIcon;
pub use SaltShakerIcon::*;
mod SandwichIcon;
pub use SandwichIcon::*;
mod SauceBottle2Icon;
pub use SauceBottle2Icon::*;
mod SauceBottleIcon;
pub use SauceBottleIcon::*;
mod SausageForkIcon;
pub use SausageForkIcon::*;
mod SausageIcon;
pub use SausageIcon::*;
mod SkewerIcon;
pub use SkewerIcon::*;
mod SmoothieIcon;
pub use SmoothieIcon::*;
mod SoftDrinkIcon;
pub use SoftDrinkIcon::*;
mod SoupIcon;
pub use SoupIcon::*;
mod SoySauceIcon;
pub use SoySauceIcon::*;
mod Steak2Icon;
pub use Steak2Icon::*;
mod SteakIcon;
pub use SteakIcon::*;
mod StoreIcon;
pub use StoreIcon::*;
mod StrawberryIcon;
pub use StrawberryIcon::*;
mod SugarDispenserIcon;
pub use SugarDispenserIcon::*;
mod SushiIcon;
pub use SushiIcon::*;
mod TacoIcon;
pub use TacoIcon::*;
mod TakeawayCoffee2Icon;
pub use TakeawayCoffee2Icon::*;
mod TakeawayCoffeeIcon;
pub use TakeawayCoffeeIcon::*;
mod TakeawayFoodIcon;
pub use TakeawayFoodIcon::*;
mod TeaBagIcon;
pub use TeaBagIcon::*;
mod TeaCupIcon;
pub use TeaCupIcon::*;
mod ToasterIcon;
pub use ToasterIcon::*;
mod TomatoIcon;
pub use TomatoIcon::*;
mod TropicalDrinkIcon;
pub use TropicalDrinkIcon::*;
mod VeganIcon;
pub use VeganIcon::*;
mod WaffleIcon;
pub use WaffleIcon::*;
mod WaterBottleIcon;
pub use WaterBottleIcon::*;
mod WatermelonSliceIcon;
pub use WatermelonSliceIcon::*;
mod WeddingCakeIcon;
pub use WeddingCakeIcon::*;
mod WhiskIcon;
pub use WhiskIcon::*;
mod WhiskeyGlassIcon;
pub use WhiskeyGlassIcon::*;
mod WineBottleIcon;
pub use WineBottleIcon::*;
mod WineGlassIcon;
pub use WineGlassIcon::*;
mod WineMenuIcon;
pub use WineMenuIcon::*;
mod YogurtCupIcon;
pub use YogurtCupIcon::*;
