#![allow(non_snake_case)]

mod AmbulanceIcon;
pub use AmbulanceIcon::*;
mod AtomIcon;
pub use AtomIcon::*;
mod BrainIcon;
pub use BrainIcon::*;
mod CallDoctorIcon;
pub use CallDoctorIcon::*;
mod CircleChartLineIcon;
pub use CircleChartLineIcon::*;
mod CondomIcon;
pub use CondomIcon::*;
mod CoughIcon;
pub use CoughIcon::*;
mod Dna2Icon;
pub use Dna2Icon::*;
mod Dna3Icon;
pub use Dna3Icon::*;
mod DnaIcon;
pub use DnaIcon::*;
mod DoctorIcon;
pub use DoctorIcon::*;
mod FertilizationIcon;
pub use FertilizationIcon::*;
mod FetusIcon;
pub use FetusIcon::*;
mod FirstAidKit2Icon;
pub use FirstAidKit2Icon::*;
mod FirstAidKitIcon;
pub use FirstAidKitIcon::*;
mod Flask2Icon;
pub use Flask2Icon::*;
mod FlaskIcon;
pub use FlaskIcon::*;
mod FootprintsIcon;
pub use FootprintsIcon::*;
mod GenderGayIcon;
pub use GenderGayIcon::*;
mod GenderLesbianIcon;
pub use GenderLesbianIcon::*;
mod HandSanitizerIcon;
pub use HandSanitizerIcon::*;
mod HandSoapIcon;
pub use HandSoapIcon::*;
mod HandsCrossIcon;
pub use HandsCrossIcon::*;
mod HeartIcon;
pub use HeartIcon::*;
mod HeartSlashIcon;
pub use HeartSlashIcon::*;
mod HeartbeatIcon;
pub use HeartbeatIcon::*;
mod HeightCheckIcon;
pub use HeightCheckIcon::*;
mod HospitalBedIcon;
pub use HospitalBedIcon::*;
mod InfectedLungsIcon;
pub use InfectedLungsIcon::*;
mod InfraredThermometerIcon;
pub use InfraredThermometerIcon::*;
mod IntestineIcon;
pub use IntestineIcon::*;
mod LungsIcon;
pub use LungsIcon::*;
mod MarsIcon;
pub use MarsIcon::*;
mod MarsVenusIcon;
pub use MarsVenusIcon::*;
mod MedicalClipboardIcon;
pub use MedicalClipboardIcon::*;
mod MedicalCross2Icon;
pub use MedicalCross2Icon::*;
mod MedicalCross3Icon;
pub use MedicalCross3Icon::*;
mod MedicalCrossIcon;
pub use MedicalCrossIcon::*;
mod MedicationIcon;
pub use MedicationIcon::*;
mod MedicineIcon;
pub use MedicineIcon::*;
mod MicrobiologyIcon;
pub use MicrobiologyIcon::*;
mod MicroscopeIcon;
pub use MicroscopeIcon::*;
mod MolecularStructureIcon;
pub use MolecularStructureIcon::*;
mod Molecule2Icon;
pub use Molecule2Icon::*;
mod MoleculeIcon;
pub use MoleculeIcon::*;
mod MoleculeStructureIcon;
pub use MoleculeStructureIcon::*;
mod NoEyeTouchIcon;
pub use NoEyeTouchIcon::*;
mod NoMouthTouchIcon;
pub use NoMouthTouchIcon::*;
mod NurseIcon;
pub use NurseIcon::*;
mod PatchIcon;
pub use PatchIcon::*;
mod PeopleAlertIcon;
pub use PeopleAlertIcon::*;
mod Person2Icon;
pub use Person2Icon::*;
mod Person3Icon;
pub use Person3Icon::*;
mod PersonDressIcon;
pub use PersonDressIcon::*;
mod PersonIcon;
pub use PersonIcon::*;
mod PharmacyBowlIcon;
pub use PharmacyBowlIcon::*;
mod PhoneHeartIcon;
pub use PhoneHeartIcon::*;
mod PhoneHeartbeatIcon;
pub use PhoneHeartbeatIcon::*;
mod Pill2Icon;
pub use Pill2Icon::*;
mod PillBottleIcon;
pub use PillBottleIcon::*;
mod PillIcon;
pub use PillIcon::*;
mod PotionIcon;
pub use PotionIcon::*;
mod PregnancyTestIcon;
pub use PregnancyTestIcon::*;
mod PulseChartIcon;
pub use PulseChartIcon::*;
mod PulseIcon;
pub use PulseIcon::*;
mod PulseSleepIcon;
pub use PulseSleepIcon::*;
mod RunnyNoseIcon;
pub use RunnyNoseIcon::*;
mod SmokingBanIcon;
pub use SmokingBanIcon::*;
mod SmokingIcon;
pub use SmokingIcon::*;
mod SneezeIcon;
pub use SneezeIcon::*;
mod SocialDistancingIcon;
pub use SocialDistancingIcon::*;
mod SpermIcon;
pub use SpermIcon::*;
mod SquareActivityChartIcon;
pub use SquareActivityChartIcon::*;
mod StethoscopeIcon;
pub use StethoscopeIcon::*;
mod StretchingIcon;
pub use StretchingIcon::*;
mod SurgicalMaskIcon;
pub use SurgicalMaskIcon::*;
mod SyringeIcon;
pub use SyringeIcon::*;
mod TapeMeasureIcon;
pub use TapeMeasureIcon::*;
mod TemperatureIcon;
pub use TemperatureIcon::*;
mod TestTubeIcon;
pub use TestTubeIcon::*;
mod ThermometerIcon;
pub use ThermometerIcon::*;
mod ToothIcon;
pub use ToothIcon::*;
mod TreadmillIcon;
pub use TreadmillIcon::*;
mod UserPhoneIcon;
pub use UserPhoneIcon::*;
mod UsersSeparationIcon;
pub use UsersSeparationIcon::*;
mod VenusIcon;
pub use VenusIcon::*;
mod VirusIcon;
pub use VirusIcon::*;
mod WalkingSupportIcon;
pub use WalkingSupportIcon::*;
mod WatchHeartIcon;
pub use WatchHeartIcon::*;
mod WatchHeartbeatIcon;
pub use WatchHeartbeatIcon::*;
mod WeightGainIcon;
pub use WeightGainIcon::*;
mod WeightLossIcon;
pub use WeightLossIcon::*;
mod WheelchairIcon;
pub use WheelchairIcon::*;
