#![allow(non_snake_case)]

mod AutomatedLogisticsIcon;
pub use AutomatedLogisticsIcon::*;
mod Bag24Icon;
pub use Bag24Icon::*;
mod BagAlertIcon;
pub use BagAlertIcon::*;
mod BagBookmarkIcon;
pub use BagBookmarkIcon::*;
mod BagChartBarIcon;
pub use BagChartBarIcon::*;
mod BagChartPieIcon;
pub use BagChartPieIcon::*;
mod BagCheckIcon;
pub use BagCheckIcon::*;
mod BagClockIcon;
pub use BagClockIcon::*;
mod BagHeartIcon;
pub use BagHeartIcon::*;
mod BagLinkIcon;
pub use BagLinkIcon::*;
mod BagMinusIcon;
pub use BagMinusIcon::*;
mod BagMoneyIcon;
pub use BagMoneyIcon::*;
mod BagPenIcon;
pub use BagPenIcon::*;
mod BagPlusIcon;
pub use BagPlusIcon::*;
mod BagRefreshIcon;
pub use BagRefreshIcon::*;
mod BagReturnIcon;
pub use BagReturnIcon::*;
mod BagSearchIcon;
pub use BagSearchIcon::*;
mod BagShareIcon;
pub use BagShareIcon::*;
mod BagUserIcon;
pub use BagUserIcon::*;
mod BagXmarkIcon;
pub use BagXmarkIcon::*;
mod BarcodeIcon;
pub use BarcodeIcon::*;
mod BarcodeScanIcon;
pub use BarcodeScanIcon::*;
mod Basket24Icon;
pub use Basket24Icon::*;
mod BasketAlertIcon;
pub use BasketAlertIcon::*;
mod BasketBookmarkIcon;
pub use BasketBookmarkIcon::*;
mod BasketChartBarIcon;
pub use BasketChartBarIcon::*;
mod BasketCheckIcon;
pub use BasketCheckIcon::*;
mod BasketClockIcon;
pub use BasketClockIcon::*;
mod BasketCoinIcon;
pub use BasketCoinIcon::*;
mod BasketFastIcon;
pub use BasketFastIcon::*;
mod BasketHeartIcon;
pub use BasketHeartIcon::*;
mod BasketLinkIcon;
pub use BasketLinkIcon::*;
mod BasketMinusIcon;
pub use BasketMinusIcon::*;
mod BasketMoneyIcon;
pub use BasketMoneyIcon::*;
mod BasketPenIcon;
pub use BasketPenIcon::*;
mod BasketPlusIcon;
pub use BasketPlusIcon::*;
mod BasketRefreshIcon;
pub use BasketRefreshIcon::*;
mod BasketReturnIcon;
pub use BasketReturnIcon::*;
mod BasketSearchIcon;
pub use BasketSearchIcon::*;
mod BasketShareIcon;
pub use BasketShareIcon::*;
mod BasketShopping2Icon;
pub use BasketShopping2Icon::*;
mod BasketShoppingIcon;
pub use BasketShoppingIcon::*;
mod BasketUserIcon;
pub use BasketUserIcon::*;
mod BasketXmarkIcon;
pub use BasketXmarkIcon::*;
mod BillIcon;
pub use BillIcon::*;
mod BillboardIcon;
pub use BillboardIcon::*;
mod Box2Icon;
pub use Box2Icon::*;
mod Box3Icon;
pub use Box3Icon::*;
mod BoxCart2Icon;
pub use BoxCart2Icon::*;
mod BoxCartIcon;
pub use BoxCartIcon::*;
mod BoxIcon;
pub use BoxIcon::*;
mod BoxRibbonIcon;
pub use BoxRibbonIcon::*;
mod BoxSearchIcon;
pub use BoxSearchIcon::*;
mod Cart24Icon;
pub use Cart24Icon::*;
mod CartAlertIcon;
pub use CartAlertIcon::*;
mod CartArrowDownIcon;
pub use CartArrowDownIcon::*;
mod CartBookmarkIcon;
pub use CartBookmarkIcon::*;
mod CartChangeIcon;
pub use CartChangeIcon::*;
mod CartChartBarIcon;
pub use CartChartBarIcon::*;
mod CartCheckIcon;
pub use CartCheckIcon::*;
mod CartClockIcon;
pub use CartClockIcon::*;
mod CartCoinIcon;
pub use CartCoinIcon::*;
mod CartFastIcon;
pub use CartFastIcon::*;
mod CartFullIcon;
pub use CartFullIcon::*;
mod CartHeartIcon;
pub use CartHeartIcon::*;
mod CartIcon;
pub use CartIcon::*;
mod CartMinusIcon;
pub use CartMinusIcon::*;
mod CartMoneyIcon;
pub use CartMoneyIcon::*;
mod CartPenIcon;
pub use CartPenIcon::*;
mod CartPinIcon;
pub use CartPinIcon::*;
mod CartPlusIcon;
pub use CartPlusIcon::*;
mod CartRefreshIcon;
pub use CartRefreshIcon::*;
mod CartReturnIcon;
pub use CartReturnIcon::*;
mod CartShareIcon;
pub use CartShareIcon::*;
mod CartSimpleAddIcon;
pub use CartSimpleAddIcon::*;
mod CartXmarkIcon;
pub use CartXmarkIcon::*;
mod CashRegisterIcon;
pub use CashRegisterIcon::*;
mod Cheque2Icon;
pub use Cheque2Icon::*;
mod CustomerSupportIcon;
pub use CustomerSupportIcon::*;
mod Discount2Icon;
pub use Discount2Icon::*;
mod DiscountCodeIcon;
pub use DiscountCodeIcon::*;
mod Drone2Icon;
pub use Drone2Icon::*;
mod DroneIcon;
pub use DroneIcon::*;
mod HandTruckIcon;
pub use HandTruckIcon::*;
mod HashtagIcon;
pub use HashtagIcon::*;
mod LifeRing2Icon;
pub use LifeRing2Icon::*;
mod LifeRingIcon;
pub use LifeRingIcon::*;
mod ListCheckIcon;
pub use ListCheckIcon::*;
mod LockIcon;
pub use LockIcon::*;
mod MobileCartIcon;
pub use MobileCartIcon::*;
mod NewIcon;
pub use NewIcon::*;
mod PalletIcon;
pub use PalletIcon::*;
mod PalletPackageIcon;
pub use PalletPackageIcon::*;
mod PercentSignIcon;
pub use PercentSignIcon::*;
mod QrcodeIcon;
pub use QrcodeIcon::*;
mod SaleIcon;
pub use SaleIcon::*;
mod ScissorsCouponIcon;
pub use ScissorsCouponIcon::*;
mod ShippingContainerIcon;
pub use ShippingContainerIcon::*;
mod ShopPinIcon;
pub use ShopPinIcon::*;
mod ShopSignIcon;
pub use ShopSignIcon::*;
mod Sign24hIcon;
pub use Sign24hIcon::*;
mod SignClosedIcon;
pub use SignClosedIcon::*;
mod SignOpenIcon;
pub use SignOpenIcon::*;
mod SignboardIcon;
pub use SignboardIcon::*;
mod StorageUnitIcon;
pub use StorageUnitIcon::*;
mod SuitcasePlayIcon;
pub use SuitcasePlayIcon::*;
mod Tag2Icon;
pub use Tag2Icon::*;
mod Tag3Icon;
pub use Tag3Icon::*;
mod TagCheckIcon;
pub use TagCheckIcon::*;
mod TagClockIcon;
pub use TagClockIcon::*;
mod TagHeartIcon;
pub use TagHeartIcon::*;
mod TagIcon;
pub use TagIcon::*;
mod TagMinusIcon;
pub use TagMinusIcon::*;
mod TagPlusIcon;
pub use TagPlusIcon::*;
mod TagsIcon;
pub use TagsIcon::*;
mod TruckClockIcon;
pub use TruckClockIcon::*;
mod TruckFastIcon;
pub use TruckFastIcon::*;
mod TruckIcon;
pub use TruckIcon::*;
mod TruckSearchIcon;
pub use TruckSearchIcon::*;
